<?php

namespace Database\Seeders;

use App\Models\Biro;
use App\Models\Unit;
use Illuminate\Database\Seeder;

class BiroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datas = [
            [
                'kode_biro' => '0000',
                'nama_biro' => '',
                'kode_deputi' => '000',
            ],
            [
                'kode_biro' => '0010',
                'nama_biro' => 'Bagian Program dan Anggaran I',
                'kode_deputi' => '001',
            ],
            [
                'kode_biro' => '0011',
                'nama_biro' => 'Bagian Program dan Anggaran II',
                'kode_deputi' => '001',
            ],
            [
                'kode_biro' => '0012',
                'nama_biro' => 'Bagian Program dan Anggaran III',
                'kode_deputi' => '001',
            ],
            [
                'kode_biro' => '0013',
                'nama_biro' => 'Bagian Pemantauan dan Evaluasi',
                'kode_deputi' => '001',
            ],
            [
                'kode_biro' => '0014',
                'nama_biro' => 'Perencana',
                'kode_deputi' => '001',
            ],
            [
                'kode_biro' => '0020',
                'nama_biro' => 'Bagian Pelaksanaan Anggaran I',
                'kode_deputi' => '002',
            ],
            [
                'kode_biro' => '0021',
                'nama_biro' => 'Bagian Pelaksanaan Anggaran II',
                'kode_deputi' => '002',
            ],
            [
                'kode_biro' => '0022',
                'nama_biro' => 'Bagian Akuntansi dan Pelaporan Keuangan',
                'kode_deputi' => '002',
            ],
            [
                'kode_biro' => '0023',
                'nama_biro' => 'Bagian Dukungan Administrasi Pelaksanaan Anggaran',
                'kode_deputi' => '002',
            ],
            [
                'kode_biro' => '0030',
                'nama_biro' => 'Bagian Persuratan dan Reproduksi',
                'kode_deputi' => '003',
            ],
            [
                'kode_biro' => '0031',
                'nama_biro' => 'Bagian Arsip',
                'kode_deputi' => '003',
            ],
            [
                'kode_biro' => '0032',
                'nama_biro' => 'Bagian Protokol dan Tata Usaha Pimpinan',
                'kode_deputi' => '003',
            ],
            [
                'kode_biro' => '0033',
                'nama_biro' => 'Bagian Perpustakaan',
                'kode_deputi' => '003',
            ],
            [
                'kode_biro' => '0034',
                'nama_biro' => 'Bagian Dukungan Pengelolaan Bahan Kebijakan',
                'kode_deputi' => '003',
            ],
            [
                'kode_biro' => '0035',
                'nama_biro' => 'Fungsional Tertentu',
                'kode_deputi' => '003',
            ],
            [
                'kode_biro' => '0036',
                'nama_biro' => 'Bagian Protokol dan Tata Usaha Pimpinan',
                'kode_deputi' => '152',
            ],
            [
                'kode_biro' => '0040',
                'nama_biro' => 'Bagian Aplikasi Sistem Informasi',
                'kode_deputi' => '004',
            ],
            [
                'kode_biro' => '0041',
                'nama_biro' => 'Bagian Infrastruktur dan Layanan Teknologi Informasi',
                'kode_deputi' => '004',
            ],
            [
                'kode_biro' => '0042',
                'nama_biro' => 'Pranata Komputer',
                'kode_deputi' => '004',
            ],
            [
                'kode_biro' => '0050',
                'nama_biro' => 'Bagian Kerja Sama Teknik Bilateral',
                'kode_deputi' => '005',
            ],
            [
                'kode_biro' => '0051',
                'nama_biro' => 'Bagian Kerja Sama Teknik Multilateral dan Organisasi Internasional Non Pemerintah',
                'kode_deputi' => '005',
            ],
            [
                'kode_biro' => '0052',
                'nama_biro' => 'Bagian Kerja Sama Teknik Selatan-Selatan dan Triangular',
                'kode_deputi' => '005',
            ],
            [
                'kode_biro' => '0053',
                'nama_biro' => 'Bagian Perjalanan Dinas Luar Negeri',
                'kode_deputi' => '005',
            ],
            [
                'kode_biro' => '0054',
                'nama_biro' => 'Bagian Fasilitas Kerja Sama Teknik dan Dukungan Administrasi',
                'kode_deputi' => '005',
            ],
            [
                'kode_biro' => '0060',
                'nama_biro' => 'Bagian Bangunan',
                'kode_deputi' => '006',
            ],
            [
                'kode_biro' => '0061',
                'nama_biro' => 'Bagian Perlengkapan dan Rumah Tangga',
                'kode_deputi' => '006',
            ],
            [
                'kode_biro' => '0062',
                'nama_biro' => 'Bagian Kendaraan',
                'kode_deputi' => '006',
            ],
            [
                'kode_biro' => '0063',
                'nama_biro' => 'Bagian Pengelolaan Barang Milik Negara',
                'kode_deputi' => '006',
            ],
            [
                'kode_biro' => '0064',
                'nama_biro' => 'Bagian Dukungan Administrasi Dokter Kepresidenan',
                'kode_deputi' => '006',
            ],
            [
                'kode_biro' => '0065',
                'nama_biro' => 'Bagian Pelayanan Kesehatan',
                'kode_deputi' => '006',
            ],
            [
                'kode_biro' => '0066',
                'nama_biro' => 'Bagian Keamanan Dalam',
                'kode_deputi' => '006',
            ],
            [
                'kode_biro' => '0068',
                'nama_biro' => 'Bagian Bangunan',
                'kode_deputi' => '156',
            ],
            [
                'kode_biro' => '0069',
                'nama_biro' => 'Bagian Kendaraan',
                'kode_deputi' => '156',
            ],
            [
                'kode_biro' => '0070',
                'nama_biro' => 'Bagian Pelayanan Kesehatan',
                'kode_deputi' => '156',
            ],
            [
                'kode_biro' => '0071',
                'nama_biro' => 'Bagian Dukungan Administrasi Dokter Kepresidenan',
                'kode_deputi' => '156',
            ],
            [
                'kode_biro' => '0072',
                'nama_biro' => 'Bagian Keamanan Dalam',
                'kode_deputi' => '156',
            ],
            [
                'kode_biro' => '0073',
                'nama_biro' => 'Bagian Pengelolaan Barang Milik Negara',
                'kode_deputi' => '1551',
            ],
            [
                'kode_biro' => '0074',
                'nama_biro' => 'Bagian Perlengkapan dan Kerumahtanggaan',
                'kode_deputi' => '156',
            ],
            [
                'kode_biro' => '0075',
                'nama_biro' => 'Bagian Administrasi dan Penatausahaan Barang Milik Negara',
                'kode_deputi' => '1551',
            ],
            [
                'kode_biro' => '0076',
                'nama_biro' => 'Bagian Pengelolaan Pengadaan Barang dan Jasa',
                'kode_deputi' => '1551',
            ],
            [
                'kode_biro' => '0077',
                'nama_biro' => 'Bagian Tata Usaha Pimpinan dan Protokol',
                'kode_deputi' => '1521',
            ],
            [
                'kode_biro' => '0100',
                'nama_biro' => 'Biro Administrasi',
                'kode_deputi' => '010',
            ],
            [
                'kode_biro' => '0101',
                'nama_biro' => 'Biro Umum',
                'kode_deputi' => '010',
            ],
            [
                'kode_biro' => '0102',
                'nama_biro' => 'Biro Pengelolaan Istana',
                'kode_deputi' => '010',
            ],
            [
                'kode_biro' => '0110',
                'nama_biro' => 'Biro Protokol',
                'kode_deputi' => '011',
            ],
            [
                'kode_biro' => '0111',
                'nama_biro' => 'Biro Pers, Media, dan Informasi',
                'kode_deputi' => '011',
            ],
            [
                'kode_biro' => '0122',
                'nama_biro' => 'Subbagian Bangunan',
                'kode_deputi' => '012',
            ],
            [
                'kode_biro' => '0123',
                'nama_biro' => 'Subbagian Perlengkapan',
                'kode_deputi' => '012',
            ],
            [
                'kode_biro' => '0130',
                'nama_biro' => 'Subbagian Tata Usaha',
                'kode_deputi' => '013',
            ],
            [
                'kode_biro' => '0131',
                'nama_biro' => 'Subbagian Rumah Tangga dan Protokol',
                'kode_deputi' => '013',
            ],
            [
                'kode_biro' => '0132',
                'nama_biro' => 'Subbagian Bangunan',
                'kode_deputi' => '013',
            ],
            [
                'kode_biro' => '0133',
                'nama_biro' => 'Subbagian Perlengkapan',
                'kode_deputi' => '013',
            ],
            [
                'kode_biro' => '0140',
                'nama_biro' => 'Subbagian Tata Usaha',
                'kode_deputi' => '014',
            ],
            [
                'kode_biro' => '0141',
                'nama_biro' => 'Subbagian Rumah Tangga dan Protokol',
                'kode_deputi' => '014',
            ],
            [
                'kode_biro' => '0142',
                'nama_biro' => 'Subbagian Bangunan',
                'kode_deputi' => '014',
            ],
            [
                'kode_biro' => '0143',
                'nama_biro' => 'Subbagian Perlengkapan',
                'kode_deputi' => '014',
            ],
            [
                'kode_biro' => '0153',
                'nama_biro' => 'Subbagian Perlengkapan',
                'kode_deputi' => '015',
            ],
            [
                'kode_biro' => '0200',
                'nama_biro' => 'Asisten Deputi Keuangan, Investasi, dan Badan Usaha',
                'kode_deputi' => '020',
            ],
            [
                'kode_biro' => '0201',
                'nama_biro' => 'Asisten Deputi Infrastruktur, Energi, dan Tata Ruang',
                'kode_deputi' => '020',
            ],
            [
                'kode_biro' => '0202',
                'nama_biro' => 'Asisten Deputi Ketahanan Pangan dan Sumber Daya Hayati',
                'kode_deputi' => '020',
            ],
            [
                'kode_biro' => '0203',
                'nama_biro' => 'Asisten Deputi Industri, Perdagangan, Pariwisata,  dan Ekonomi Kreatif',
                'kode_deputi' => '020',
            ],
            [
                'kode_biro' => '0204',
                'nama_biro' => 'Asisten Deputi Ekonomi dan Keuangan',
                'kode_deputi' => '024',
            ],
            [
                'kode_biro' => '0205',
                'nama_biro' => 'Asisten Deputi Industri, Perdagangan, Pariwisata, dan Ekonomi Kreatif',
                'kode_deputi' => '024',
            ],
            [
                'kode_biro' => '0206',
                'nama_biro' => 'Asisten Deputi Infrastruktur, Ketahanan Energi, dan Sumber Daya Alam',
                'kode_deputi' => '024',
            ],
            [
                'kode_biro' => '0210',
                'nama_biro' => 'Asisten Deputi Pembangunan Sumber Daya Manusia',
                'kode_deputi' => '021',
            ],
            [
                'kode_biro' => '0211',
                'nama_biro' => 'Asisten Deputi Perlindungan Sosial dan Penanggulangan Bencana',
                'kode_deputi' => '021',
            ],
            [
                'kode_biro' => '0212',
                'nama_biro' => 'Asisten Deputi Peningkatan dan Pengembangan Kesejahteraan',
                'kode_deputi' => '021',
            ],
            [
                'kode_biro' => '0213',
                'nama_biro' => 'Asisten Deputi Penanggulangan Kemiskinan',
                'kode_deputi' => '025',
            ],
            [
                'kode_biro' => '0214',
                'nama_biro' => 'Asisten Deputi Pembangunan Sumber Daya Manusia',
                'kode_deputi' => '025',
            ],
            [
                'kode_biro' => '0215',
                'nama_biro' => 'Asisten Deputi Pemberdayaan Masyarakat dan Penanggulangan Bencana',
                'kode_deputi' => '025',
            ],
            [
                'kode_biro' => '0220',
                'nama_biro' => 'Asisten Deputi Politik, Hukum, dan Keamanan',
                'kode_deputi' => '022',
            ],
            [
                'kode_biro' => '0221',
                'nama_biro' => 'Asisten Deputi Hubungan Luar Negeri',
                'kode_deputi' => '022',
            ],
            [
                'kode_biro' => '0222',
                'nama_biro' => 'Asisten Deputi Reformasi Birokrasi dan Pelayanan Publik',
                'kode_deputi' => '022',
            ],
            [
                'kode_biro' => '0223',
                'nama_biro' => 'Asisten Deputi Pengawasan Penyelenggaraan Pemerintahan',
                'kode_deputi' => '022',
            ],
            [
                'kode_biro' => '0224',
                'nama_biro' => 'Asisten Deputi Komunikasi dan Informasi Publik ',
                'kode_deputi' => '022',
            ],
            [
                'kode_biro' => '0225',
                'nama_biro' => 'Asisten Deputi Hubungan Luar Negeri',
                'kode_deputi' => '026',
            ],
            [
                'kode_biro' => '0226',
                'nama_biro' => 'Asisten Deputi Politik, Hukum, dan Otonomi Daerah',
                'kode_deputi' => '026',
            ],
            [
                'kode_biro' => '0227',
                'nama_biro' => 'Asisten Deputi Wawasan Kebangsaan, Pertahanan, dan Keamanan',
                'kode_deputi' => '026',
            ],
            [
                'kode_biro' => '0228',
                'nama_biro' => 'Asisten Deputi Tata Kelola Pemerintahan',
                'kode_deputi' => '026',
            ],
            [
                'kode_biro' => '0230',
                'nama_biro' => 'Biro Protokol ',
                'kode_deputi' => '023',
            ],
            [
                'kode_biro' => '0231',
                'nama_biro' => 'Biro Perencanaan dan Keuangan',
                'kode_deputi' => '023',
            ],
            [
                'kode_biro' => '0232',
                'nama_biro' => 'Biro Tata Usaha,Teknologi Informasi, dan Kepegawaian',
                'kode_deputi' => '023',
            ],
            [
                'kode_biro' => '0233',
                'nama_biro' => 'Biro Umum ',
                'kode_deputi' => '023',
            ],
            [
                'kode_biro' => '0234',
                'nama_biro' => 'Biro Protokol dan Kerumahtanggaan',
                'kode_deputi' => '027',
            ],
            [
                'kode_biro' => '0235',
                'nama_biro' => 'Biro Pers, Media, dan Informasi',
                'kode_deputi' => '027',
            ],
            [
                'kode_biro' => '0236',
                'nama_biro' => 'Biro Perencanaan dan Keuangan',
                'kode_deputi' => '027',
            ],
            [
                'kode_biro' => '0237',
                'nama_biro' => 'Biro Tata Usaha, Teknologi Informasi, dan Kepegawaian',
                'kode_deputi' => '027',
            ],
            [
                'kode_biro' => '0238',
                'nama_biro' => 'Biro Umum ',
                'kode_deputi' => '027',
            ],
            [
                'kode_biro' => '0239',
                'nama_biro' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'kode_deputi' => '027',
            ],
            [
                'kode_biro' => '0281',
                'nama_biro' => 'Asisten Deputi Ekonomi, Keuangan, dan Transformasi Digital',
                'kode_deputi' => '028',
            ],
            [
                'kode_biro' => '0282',
                'nama_biro' => 'Asisten Deputi Industri, Perdagangan, Pariwisata, dan Ekonomi Kreatif',
                'kode_deputi' => '028',
            ],
            [
                'kode_biro' => '0283',
                'nama_biro' => 'Asisten Deputi Infrastruktur, Sumber Daya Alam, dan Pembangunan Kewilayahan',
                'kode_deputi' => '028',
            ],
            [
                'kode_biro' => '0291',
                'nama_biro' => 'Asisten Deputi Pengentasan Kemiskinan dan Pembangunan Desa',
                'kode_deputi' => '029',
            ],
            [
                'kode_biro' => '0292',
                'nama_biro' => 'Asisten Deputi Kesehatan, Gizi, dan Pembangunan Keluarga',
                'kode_deputi' => '029',
            ],
            [
                'kode_biro' => '0293',
                'nama_biro' => 'Asisten Deputi Pemberdayaan Masyarakat dan Penanggulangan Bencana',
                'kode_deputi' => '029',
            ],
            [
                'kode_biro' => '0294',
                'nama_biro' => 'Asisten Deputi Pendidikan, Agama, Kebudayaan, Pemuda, dan Olahraga ',
                'kode_deputi' => '029',
            ],
            [
                'kode_biro' => '0300',
                'nama_biro' => 'Bagian Pengangkatan dan Pemberhentian TNI dan Polri',
                'kode_deputi' => '030',
            ],
            [
                'kode_biro' => '0301',
                'nama_biro' => 'Bagian Pembinaan Personel TNI dan Polri',
                'kode_deputi' => '030',
            ],
            [
                'kode_biro' => '0302',
                'nama_biro' => 'Bagian Administrasi dan Pengelolaan Data',
                'kode_deputi' => '030',
            ],
            [
                'kode_biro' => '0303',
                'nama_biro' => 'Bagian Pengangkatan dan Pemberhentian TNI dan Polri',
                'kode_deputi' => '030',
            ],
            [
                'kode_biro' => '0304',
                'nama_biro' => 'Bagian Dukungan Pembinaan dan Pelayanan Personel TNI dan Polri',
                'kode_deputi' => '030',
            ],
            [
                'kode_biro' => '0305',
                'nama_biro' => 'Bagian Administrasi dan Pengelolaan Data',
                'kode_deputi' => '030',
            ],
            [
                'kode_biro' => '0310',
                'nama_biro' => 'Bagian Operasi Pengamanan',
                'kode_deputi' => '031',
            ],
            [
                'kode_biro' => '03100',
                'nama_biro' => 'Asisten Deputi Hukum, Hak Asasi Manusia, Imigrasi, dan Pemasyarakatan',
                'kode_deputi' => '0310',
            ],
            [
                'kode_biro' => '03101',
                'nama_biro' => 'Asisten Deputi Politik, Pemerintahan Dalam Negeri dan Aparatur Negara',
                'kode_deputi' => '0310',
            ],
            [
                'kode_biro' => '03102',
                'nama_biro' => 'Asisten Deputi Hubungan Luar Negeri, Komunikasi, dan Digital',
                'kode_deputi' => '0310',
            ],
            [
                'kode_biro' => '03103',
                'nama_biro' => 'Asisten Deputi Pertahanan dan Keamanan',
                'kode_deputi' => '0310',
            ],
            [
                'kode_biro' => '0311',
                'nama_biro' => 'Bagian Penyelidikan dan Pengamanan Khusus',
                'kode_deputi' => '031',
            ],
            [
                'kode_biro' => '03110',
                'nama_biro' => 'Asisten Deputi Perencanaan Pembangunan, Fiskal, dan Pengembangan Badan Usaha Milik Negara',
                'kode_deputi' => '0311',
            ],
            [
                'kode_biro' => '03111',
                'nama_biro' => 'Asisten Deputi Ketenagakerjaan, Investasi, dan Hilirisasi',
                'kode_deputi' => '0311',
            ],
            [
                'kode_biro' => '03112',
                'nama_biro' => 'Asisten Deputi Energi, Sumber Daya Mineral, dan Pariwisata',
                'kode_deputi' => '0311',
            ],
            [
                'kode_biro' => '03113',
                'nama_biro' => 'Asisten Deputi Perdagangan dan Perindustrian',
                'kode_deputi' => '0311',
            ],
            [
                'kode_biro' => '0312',
                'nama_biro' => 'Bagian Administrasi Pengamanan',
                'kode_deputi' => '031',
            ],
            [
                'kode_biro' => '03120',
                'nama_biro' => 'Asisten Deputi Kesehatan, Kependudukan, Pemuda, dan Olahraga',
                'kode_deputi' => '0312',
            ],
            [
                'kode_biro' => '03121',
                'nama_biro' => 'Asisten Deputi Agama, Kebudayaan, Pendidikan, Sains, dan Teknologi',
                'kode_deputi' => '0312',
            ],
            [
                'kode_biro' => '03122',
                'nama_biro' => 'Asisten Deputi Sosial, Pekerja Migran, Pemberdayaan Perempuan, dan Perlindungan Anak',
                'kode_deputi' => '0312',
            ],
            [
                'kode_biro' => '03123',
                'nama_biro' => 'Asisten Deputi Desa, Pembangunan Daerah Tertinggal, Koperasi, Usaha Mikro, Kecil, dan Menengah, dan Ekonomi Kreatif',
                'kode_deputi' => '0312',
            ],
            [
                'kode_biro' => '0313',
                'nama_biro' => 'Bagian Keamanan dan Ketertiban Dalam',
                'kode_deputi' => '031',
            ],
            [
                'kode_biro' => '03130',
                'nama_biro' => 'Asisten Deputi Kelautan, Perikanan, dan Kehutanan',
                'kode_deputi' => '0313',
            ],
            [
                'kode_biro' => '03131',
                'nama_biro' => 'Asisten Deputi Pertanian, Pangan, dan Gizi',
                'kode_deputi' => '0313',
            ],
            [
                'kode_biro' => '03132',
                'nama_biro' => 'Asisten Deputi Agraria, Tata Ruang, Transmigrasi, dan Lingkungan Hidup',
                'kode_deputi' => '0313',
            ],
            [
                'kode_biro' => '03133',
                'nama_biro' => 'Asisten Deputi Pekerjaan Umum, Perumahan, dan Perhubungan',
                'kode_deputi' => '0313',
            ],
            [
                'kode_biro' => '03140',
                'nama_biro' => 'Asisten Deputi Penyelenggaraan Persidangan',
                'kode_deputi' => '0314',
            ],
            [
                'kode_biro' => '03141',
                'nama_biro' => 'Asisten Deputi Pelaporan Persidangan',
                'kode_deputi' => '0314',
            ],
            [
                'kode_biro' => '03142',
                'nama_biro' => 'Asisten Deputi Naskah dan Penerjemahan',
                'kode_deputi' => '0314',
            ],
            [
                'kode_biro' => '03143',
                'nama_biro' => 'Asisten Deputi Dokumentasi, Diseminasi, dan Arsip Kepresidenan dan Kementerian',
                'kode_deputi' => '0314',
            ],
            [
                'kode_biro' => '03150',
                'nama_biro' => 'Biro Pengelolaan Anggaran, Sumber Daya Manusia, dan Kinerja',
                'kode_deputi' => '0315',
            ],
            [
                'kode_biro' => '03151',
                'nama_biro' => 'Biro Dukungan Aparatur dan Kelembagaan',
                'kode_deputi' => '0315',
            ],
            [
                'kode_biro' => '03152',
                'nama_biro' => 'Biro Umum',
                'kode_deputi' => '0315',
            ],
            [
                'kode_biro' => '0320',
                'nama_biro' => 'Bagian Administrasi',
                'kode_deputi' => '032',
            ],
            [
                'kode_biro' => '0321',
                'nama_biro' => 'Bagian Verifikasi Gelar, Tanda Jasa, dan Tanda Kehormatan',
                'kode_deputi' => '032',
            ],
            [
                'kode_biro' => '0322',
                'nama_biro' => 'Bagian Penganugerahan',
                'kode_deputi' => '032',
            ],
            [
                'kode_biro' => '0323',
                'nama_biro' => 'Bagian Penganugerahan',
                'kode_deputi' => '032',
            ],
            [
                'kode_biro' => '0324',
                'nama_biro' => 'Bagian Verifikasi dan Administrasi Gelar, Tanda Jasa, dan Tanda Kehormatan',
                'kode_deputi' => '032',
            ],
            [
                'kode_biro' => '0330',
                'nama_biro' => 'Bagian Perencanaan dan Evaluasi',
                'kode_deputi' => '033',
            ],
            [
                'kode_biro' => '0331',
                'nama_biro' => 'Bagian Kepegawaian dan Keuangan',
                'kode_deputi' => '033',
            ],
            [
                'kode_biro' => '0332',
                'nama_biro' => 'Bagian Tata Usaha dan Perlengkapan',
                'kode_deputi' => '033',
            ],
            [
                'kode_biro' => '0333',
                'nama_biro' => 'Bagian Tata Usaha dan Layanan Pengadaan',
                'kode_deputi' => '033',
            ],
            [
                'kode_biro' => '0340',
                'nama_biro' => 'Dokter Pribadi Presiden/Wakil Presiden',
                'kode_deputi' => '034',
            ],
            [
                'kode_biro' => '0341',
                'nama_biro' => 'Ketua/Wakil Ketua Tim Dokter Kepresidenan',
                'kode_deputi' => '034',
            ],
            [
                'kode_biro' => '0350',
                'nama_biro' => 'Ajudan Presiden',
                'kode_deputi' => '035',
            ],
            [
                'kode_biro' => '0351',
                'nama_biro' => 'Ajudan Wakil Presiden',
                'kode_deputi' => '035',
            ],
            [
                'kode_biro' => '0352',
                'nama_biro' => 'Ajudan Istri Presiden',
                'kode_deputi' => '035',
            ],
            [
                'kode_biro' => '0353',
                'nama_biro' => 'Ajudan Istri Wakil Presiden',
                'kode_deputi' => '035',
            ],
            [
                'kode_biro' => '0354',
                'nama_biro' => 'Ajudan Istri/Suami Presiden',
                'kode_deputi' => '035',
            ],
            [
                'kode_biro' => '0355',
                'nama_biro' => 'Ajudan Istri/Suami Wakil Presiden',
                'kode_deputi' => '035',
            ],
            [
                'kode_biro' => '0360',
                'nama_biro' => 'Asisten Sekretaris Kabinet',
                'kode_deputi' => '036',
            ],
            [
                'kode_biro' => '0371',
                'nama_biro' => 'Asisten Deputi Hubungan Luar Negeri dan Pertahanan',
                'kode_deputi' => '037',
            ],
            [
                'kode_biro' => '0372',
                'nama_biro' => 'Asisten Deputi Politik, Keamanan, Hukum, dan Hak Asasi Manusia',
                'kode_deputi' => '037',
            ],
            [
                'kode_biro' => '0373',
                'nama_biro' => 'Asisten Deputi Tata Kelola Pemerintahan dan Percepatan Pembangunan Daerah ',
                'kode_deputi' => '037',
            ],
            [
                'kode_biro' => '0400',
                'nama_biro' => 'Bidang Pertahanan dan Keamanan ',
                'kode_deputi' => '040',
            ],
            [
                'kode_biro' => '0401',
                'nama_biro' => 'Bidang Politik dan Pemerintahan Umum',
                'kode_deputi' => '040',
            ],
            [
                'kode_biro' => '0402',
                'nama_biro' => 'Bidang Hukum dan Hak Asasi Manusia',
                'kode_deputi' => '040',
            ],
            [
                'kode_biro' => '0403',
                'nama_biro' => 'Bidang Aparatur Negara',
                'kode_deputi' => '040',
            ],
            [
                'kode_biro' => '0410',
                'nama_biro' => 'Bidang Agama, Pendidikan, Riset, dan Teknologi',
                'kode_deputi' => '041',
            ],
            ['kode_biro' => '0411', 'nama_biro' => 'Bidang Kesejahteraan Sosial', 'kode_deputi' => '041', 'created_at' => NULL,],
            ['kode_biro' => '0412', 'nama_biro' => 'Bidang Pariwisata, Kebudayaan, Perlindungan, dan Pemberdayaan Manusia', 'kode_deputi' => '041', 'created_at' => NULL,],
            ['kode_biro' => '0420', 'nama_biro' => 'Bidang Moneter dan Jasa Keuangan', 'kode_deputi' => '042', 'created_at' => NULL,],
            ['kode_biro' => '0421', 'nama_biro' => 'Bidang Sumber Daya Alam,  Lingkungan Hidup, dan Kehutanan', 'kode_deputi' => '042', 'created_at' => NULL,],
            ['kode_biro' => '0422', 'nama_biro' => 'Bidang Prasarana, Agraria dan Tata Ruang', 'kode_deputi' => '042', 'created_at' => NULL,],
            ['kode_biro' => '0423', 'nama_biro' => 'Bidang Perindustrian, Perdagangan, dan Badan Usaha', 'kode_deputi' => '042', 'created_at' => NULL,],
            ['kode_biro' => '0430', 'nama_biro' => 'Bidang Pemerintahan Dalam Negeri', 'kode_deputi' => '043', 'created_at' => NULL,],
            ['kode_biro' => '0431', 'nama_biro' => 'Bidang Otonomi Daerah', 'kode_deputi' => '043', 'created_at' => NULL,],
            ['kode_biro' => '0432', 'nama_biro' => 'Bidang Pembangunan Daerah', 'kode_deputi' => '043', 'created_at' => NULL,],
            ['kode_biro' => '0433', 'nama_biro' => 'Bidang Keuangan Daerah', 'kode_deputi' => '043', 'created_at' => NULL,],
            ['kode_biro' => '0440', 'nama_biro' => 'Bidang Litigasi dan Permasalahan Hukum', 'kode_deputi' => '044', 'created_at' => NULL,],
            ['kode_biro' => '0441', 'nama_biro' => 'Bidang Perjanjian Internasional', 'kode_deputi' => '044', 'created_at' => NULL,],
            ['kode_biro' => '0442', 'nama_biro' => 'Bidang Prerogatif dan Naturalisasi', 'kode_deputi' => '044', 'created_at' => NULL,],
            ['kode_biro' => '0443', 'nama_biro' => 'Bidang Distribusi, Publikasi, dan Dokumentasi', 'kode_deputi' => '044', 'created_at' => NULL,],
            ['kode_biro' => '0450', 'nama_biro' => 'Subbagian Dukungan Administrasi', 'kode_deputi' => '045', 'created_at' => NULL,],
            ['kode_biro' => '0460', 'nama_biro' => 'Subbagian Dukungan Administrasi', 'kode_deputi' => '046', 'created_at' => NULL,],
            ['kode_biro' => '0470', 'nama_biro' => 'Subbagian Dukungan Administrasi', 'kode_deputi' => '047', 'created_at' => NULL,],
            ['kode_biro' => '0480', 'nama_biro' => 'Subbagian Dukungan Administrasi', 'kode_deputi' => '048', 'created_at' => NULL,],
            ['kode_biro' => '0490', 'nama_biro' => 'Bagian Dukungan Administrasi', 'kode_deputi' => '049', 'created_at' => NULL,],
            ['kode_biro' => '0500', 'nama_biro' => 'Bidang Bidang Hubungan Lembaga Negara I', 'kode_deputi' => '050', 'created_at' => NULL,],
            ['kode_biro' => '0501', 'nama_biro' => 'Bidang Hubungan Lembaga Negara II', 'kode_deputi' => '050', 'created_at' => NULL,],
            ['kode_biro' => '0502', 'nama_biro' => 'Bidang Hubungan Lembaga Non Struktural', 'kode_deputi' => '050', 'created_at' => NULL,],
            ['kode_biro' => '0503', 'nama_biro' => 'Bidang Hubungan Lembaga Daerah', 'kode_deputi' => '050', 'created_at' => NULL,],
            ['kode_biro' => '0510', 'nama_biro' => 'Bidang Hubungan Organisasi Kemasyarakatan I', 'kode_deputi' => '051', 'created_at' => NULL,],
            ['kode_biro' => '0511', 'nama_biro' => 'Bidang Hubungan Organisasi Kemasyarakatan II', 'kode_deputi' => '051', 'created_at' => NULL,],
            ['kode_biro' => '0512', 'nama_biro' => 'Bidang Hubungan Yayasan dan Badan Usaha', 'kode_deputi' => '051', 'created_at' => NULL,],
            ['kode_biro' => '0513', 'nama_biro' => 'Bidang Hubungan Organisasi Politik', 'kode_deputi' => '051', 'created_at' => NULL,],
            ['kode_biro' => '0520', 'nama_biro' => 'Bidang Hukum dan Hak Asasi Manusia', 'kode_deputi' => '052', 'created_at' => NULL,],
            ['kode_biro' => '0521', 'nama_biro' => 'Bidang Pelayanan Publik, Aparatur, dan Ketenagakerjaan', 'kode_deputi' => '052', 'created_at' => NULL,],
            ['kode_biro' => '0522', 'nama_biro' => 'Bidang Agraria dan Lingkungan Hidup', 'kode_deputi' => '052', 'created_at' => NULL,],
            ['kode_biro' => '0523', 'nama_biro' => 'Bidang Data, Evaluasi, dan Pelaporan', 'kode_deputi' => '052', 'created_at' => NULL,],
            ['kode_biro' => '0530', 'nama_biro' => 'Bidang Pengelolaan Informasi Publik', 'kode_deputi' => '053', 'created_at' => NULL,],
            ['kode_biro' => '0531', 'nama_biro' => 'Bidang Monitoring dan Analisis Media', 'kode_deputi' => '053', 'created_at' => NULL,],
            ['kode_biro' => '0532', 'nama_biro' => 'Bidang Peliputan dan Dokumentasi', 'kode_deputi' => '053', 'created_at' => NULL,],
            ['kode_biro' => '0533', 'nama_biro' => 'Bidang Diseminasi Informasi', 'kode_deputi' => '053', 'created_at' => NULL,],
            ['kode_biro' => '0540', 'nama_biro' => 'Subbagian Dukungan Administrasi', 'kode_deputi' => '054', 'created_at' => NULL,],
            ['kode_biro' => '0550', 'nama_biro' => 'Bagian Dukungan Administrasi', 'kode_deputi' => '055', 'created_at' => NULL,],
            ['kode_biro' => '0560', 'nama_biro' => 'Subbagian Dukungan Administrasi', 'kode_deputi' => '056', 'created_at' => NULL,],
            ['kode_biro' => '0570', 'nama_biro' => 'Subbagian Dukungan Administrasi', 'kode_deputi' => '057', 'created_at' => NULL,],
            ['kode_biro' => '0580', 'nama_biro' => 'Subbagian Dukungan Administrasi', 'kode_deputi' => '058', 'created_at' => NULL,],
            ['kode_biro' => '0600', 'nama_biro' => 'Bagian Pengangkatan, Pemberhentian, dan Pensiun Pejabat Negara', 'kode_deputi' => '060', 'created_at' => NULL,],
            ['kode_biro' => '0601', 'nama_biro' => 'Bagian Informasi Pejabat Negara ', 'kode_deputi' => '060', 'created_at' => NULL,],
            ['kode_biro' => '0610', 'nama_biro' => 'Bagian Pengangkatan dan Pemberhentian Pejabat Pemerintahan ', 'kode_deputi' => '061', 'created_at' => NULL,],
            ['kode_biro' => '06101', 'nama_biro' => 'Bagian Dukungan Administrasi', 'kode_deputi' => '0610', 'created_at' => NULL,],
            ['kode_biro' => '0611', 'nama_biro' => 'Bagian Kepangkatan', 'kode_deputi' => '061', 'created_at' => NULL,],
            ['kode_biro' => '06111', 'nama_biro' => 'Subbagian Dukungan Administrasi', 'kode_deputi' => '0611', 'created_at' => NULL,],
            ['kode_biro' => '0612', 'nama_biro' => 'Bagian Pemberhentian', 'kode_deputi' => '061', 'created_at' => NULL,],
            ['kode_biro' => '06121', 'nama_biro' => 'Subbagian Dukungan Administrasi', 'kode_deputi' => '0612', 'created_at' => NULL,],
            ['kode_biro' => '0613', 'nama_biro' => 'Bagian Administrasi Umum', 'kode_deputi' => '061', 'created_at' => NULL,],
            ['kode_biro' => '0620', 'nama_biro' => 'Bagian Perencanaan, Informasi, dan Kinerja Sumber Daya Manusia', 'kode_deputi' => '062', 'created_at' => NULL,],
            ['kode_biro' => '0621', 'nama_biro' => 'Bagian Mutasi', 'kode_deputi' => '062', 'created_at' => NULL,],
            ['kode_biro' => '0622', 'nama_biro' => 'Bagian Disiplin, Kesejahteraan, dan Tata Usaha', 'kode_deputi' => '062', 'created_at' => NULL,],
            ['kode_biro' => '0623', 'nama_biro' => 'Analis Kepegawaian', 'kode_deputi' => '062', 'created_at' => NULL,],
            ['kode_biro' => '0630', 'nama_biro' => 'Bagian Organisasi ', 'kode_deputi' => '063', 'created_at' => NULL,],
            ['kode_biro' => '0631', 'nama_biro' => 'Bagian Tata Laksana', 'kode_deputi' => '063', 'created_at' => NULL,],
            ['kode_biro' => '0632', 'nama_biro' => 'Bagian Akuntabilitas Kinerja I', 'kode_deputi' => '063', 'created_at' => NULL,],
            ['kode_biro' => '0633', 'nama_biro' => 'Bagian Akuntabilitas Kinerja II', 'kode_deputi' => '063', 'created_at' => NULL,],
            ['kode_biro' => '0640', 'nama_biro' => 'Subbagian Dukungan Administrasi', 'kode_deputi' => '064', 'created_at' => NULL,],
            ['kode_biro' => '0650', 'nama_biro' => 'Bagian Dukungan Administrasi', 'kode_deputi' => '065', 'created_at' => NULL,],
            ['kode_biro' => '0660', 'nama_biro' => 'TB/CLTN/Non Job', 'kode_deputi' => '066', 'created_at' => NULL,],
            ['kode_biro' => '0661', 'nama_biro' => 'Subbagian Dukungan Administrasi', 'kode_deputi' => '066', 'created_at' => NULL,],
            ['kode_biro' => '0670', 'nama_biro' => 'Subbagian Dukungan Administrasi', 'kode_deputi' => '067', 'created_at' => NULL,],
            ['kode_biro' => '0900', 'nama_biro' => 'Subbagian Tata Usaha ', 'kode_deputi' => '090', 'created_at' => NULL,],
            ['kode_biro' => '0901', 'nama_biro' => 'Subbagian Administrasi Tindak Lanjut Hasil Pengawasan', 'kode_deputi' => '090', 'created_at' => NULL,],
            ['kode_biro' => '1000', 'nama_biro' => 'Subbidang Perencanaan dan Akademik', 'kode_deputi' => '100', 'created_at' => NULL,],
            ['kode_biro' => '1001', 'nama_biro' => 'Subbidang Evaluasi dan Pelaporan', 'kode_deputi' => '100', 'created_at' => NULL,],
            ['kode_biro' => '1010', 'nama_biro' => 'Subbidang Penyelenggaraan Pelatihan Kepemimpinan', 'kode_deputi' => '101', 'created_at' => NULL,],
            ['kode_biro' => '1011', 'nama_biro' => 'Subbidang Penyelenggaraan Pelatihan Prajabatan dan Beasiswa Pendidikan', 'kode_deputi' => '101', 'created_at' => NULL,],
            ['kode_biro' => '1020', 'nama_biro' => 'Subbidang Penyelenggaraan Pelatihan Teknis ', 'kode_deputi' => '102', 'created_at' => NULL,],
            ['kode_biro' => '1021', 'nama_biro' => 'Subbidang Penyelenggaraan Pelatihan Fungsional', 'kode_deputi' => '102', 'created_at' => NULL,],
            ['kode_biro' => '1030', 'nama_biro' => 'Subbagian Data dan Informasi', 'kode_deputi' => '103', 'created_at' => NULL,],
            ['kode_biro' => '1031', 'nama_biro' => 'Subbagian Kerumahtanggaan', 'kode_deputi' => '103', 'created_at' => NULL,],
            ['kode_biro' => '1032', 'nama_biro' => 'Subbagian Umum', 'kode_deputi' => '103', 'created_at' => NULL,],
            ['kode_biro' => '1200', 'nama_biro' => 'Bagian Politik, Hukum, dan Keamanan Negara', 'kode_deputi' => '120', 'created_at' => NULL,],
            ['kode_biro' => '12000', 'nama_biro' => 'Subbagian Tata Usaha', 'kode_deputi' => '012', 'created_at' => NULL,],
            ['kode_biro' => '1201', 'nama_biro' => 'Bagian Perekonomian', 'kode_deputi' => '120', 'created_at' => NULL,],
            ['kode_biro' => '1202', 'nama_biro' => 'Bagian Kesejahteraan Rakyat', 'kode_deputi' => '120', 'created_at' => NULL,],
            ['kode_biro' => '1210', 'nama_biro' => 'Bagian Tata Usaha, Program, dan Anggaran', 'kode_deputi' => '121', 'created_at' => NULL,],
            ['kode_biro' => '12100', 'nama_biro' => 'Subbagian Rumah Tangga dan Protokol', 'kode_deputi' => '012', 'created_at' => NULL,],
            ['kode_biro' => '1211', 'nama_biro' => 'Bagian Keuangan', 'kode_deputi' => '121', 'created_at' => NULL,],
            ['kode_biro' => '1212', 'nama_biro' => 'Bagian Perlengkapan, Keprotokolan dan Persidangan', 'kode_deputi' => '121', 'created_at' => NULL,],
            ['kode_biro' => '1213', 'nama_biro' => 'Kepala Bagian Tata Usaha, Rumah Tangga, dan Protokol', 'kode_deputi' => '121', 'created_at' => NULL,],
            ['kode_biro' => '1500', 'nama_biro' => 'Subbagian Tata Usaha', 'kode_deputi' => '015', 'created_at' => NULL,],
            ['kode_biro' => '1501', 'nama_biro' => 'Bagian Dukungan Administrasi', 'kode_deputi' => '150', 'created_at' => NULL,],
            ['kode_biro' => '1510', 'nama_biro' => 'Subbagian Rumah Tangga dan Protokol', 'kode_deputi' => '015', 'created_at' => NULL,],
            ['kode_biro' => '1511', 'nama_biro' => 'Bagian Dukungan Administrasi', 'kode_deputi' => '151', 'created_at' => NULL,],
            ['kode_biro' => '1520', 'nama_biro' => 'Subbagian Bangunan', 'kode_deputi' => '015', 'created_at' => NULL,],
            ['kode_biro' => '1530', 'nama_biro' => 'Subbagian Protokol dan Layanan', 'kode_deputi' => '015', 'created_at' => NULL,],
            ['kode_biro' => '1541', 'nama_biro' => 'Bagian Dukungan Administrasi', 'kode_deputi' => '154', 'created_at' => NULL,],
            ['kode_biro' => '1551', 'nama_biro' => 'Bagian Dukungan Administrasi', 'kode_deputi' => '155', 'created_at' => NULL,],
            ['kode_biro' => '1601', 'nama_biro' => 'Subbagian Dukungan Administrasi', 'kode_deputi' => '160', 'created_at' => NULL,],
            ['kode_biro' => '1611', 'nama_biro' => 'Subbagian Dukungan Administrasi', 'kode_deputi' => '161', 'created_at' => NULL,],
            ['kode_biro' => '1621', 'nama_biro' => 'Subbagian Dukungan Administrasi', 'kode_deputi' => '162', 'created_at' => NULL,],
            ['kode_biro' => '167000', 'nama_biro' => 'Subbagian Perencanaan', 'kode_deputi' => '16700', 'created_at' => NULL,],
            ['kode_biro' => '167001', 'nama_biro' => 'Subbagian Keuangan', 'kode_deputi' => '16700', 'created_at' => NULL,],
            ['kode_biro' => '167002', 'nama_biro' => 'Subbagian Akuntabilitas Kinerja', 'kode_deputi' => '16700', 'created_at' => NULL,],
            ['kode_biro' => '167010', 'nama_biro' => 'Subbagian Kepegawaian dan Tata Laksana', 'kode_deputi' => '16701', 'created_at' => NULL,],
            ['kode_biro' => '167011', 'nama_biro' => 'Subbagian Tata Usaha dan Protokol', 'kode_deputi' => '16701', 'created_at' => NULL,],
            ['kode_biro' => '167012', 'nama_biro' => 'Subbagian Teknologi Informasi', 'kode_deputi' => '16701', 'created_at' => NULL,],
            ['kode_biro' => '167020', 'nama_biro' => 'Subbagian Rumah Tangga', 'kode_deputi' => '16702', 'created_at' => NULL,],
            ['kode_biro' => '167021', 'nama_biro' => 'Subbagian Penatausahaan Barang Milik Negara (BMN)', 'kode_deputi' => '16702', 'created_at' => NULL,],
            ['kode_biro' => '167022', 'nama_biro' => 'Subbagian Administrasi Pengadaan Barang dan/atau Jasa', 'kode_deputi' => '16702', 'created_at' => NULL,],
            ['kode_biro' => '2000', 'nama_biro' => 'Subbagian Perencanaan', 'kode_deputi' => '200', 'created_at' => NULL,],
            ['kode_biro' => '2001', 'nama_biro' => 'Subbagian Keuangan', 'kode_deputi' => '200', 'created_at' => NULL,],
            ['kode_biro' => '2002', 'nama_biro' => 'Subbagian Ketatalaksanaan dan Manajemen Kinerja', 'kode_deputi' => '200', 'created_at' => NULL,],
            ['kode_biro' => '2010', 'nama_biro' => 'Subbagian Kepegawaian', 'kode_deputi' => '201', 'created_at' => NULL,],
            ['kode_biro' => '2011', 'nama_biro' => 'Subbagian Tata Usaha', 'kode_deputi' => '201', 'created_at' => NULL,],
            ['kode_biro' => '2012', 'nama_biro' => 'Subbagian Perlengkapan dan Kerumahtanggaan', 'kode_deputi' => '201', 'created_at' => NULL,],
            ['kode_biro' => '2020', 'nama_biro' => 'Subbagian Pengelolaan Data dan Informasi', 'kode_deputi' => '202', 'created_at' => NULL,],
            ['kode_biro' => '2021', 'nama_biro' => 'Subbagian Pengelolaan Infrastruktur Teknologi Informasi', 'kode_deputi' => '202', 'created_at' => NULL,],
            ['kode_biro' => '2022', 'nama_biro' => 'Subbagian Pengelolaan Keamanan Informasi', 'kode_deputi' => '202', 'created_at' => NULL,],
            ['kode_biro' => '2030', 'nama_biro' => 'Kepala Subbagian Tata Usaha dan Protokol', 'kode_deputi' => '203', 'created_at' => NULL,],
            ['kode_biro' => '2031', 'nama_biro' => 'Kepala Subbagian Perlengkapan dan Rumah Tangga', 'kode_deputi' => '203', 'created_at' => NULL,],
            ['kode_biro' => '2121', 'nama_biro' => 'Subbagian Tata Usaha', 'kode_deputi' => '212', 'created_at' => NULL,],
            ['kode_biro' => '2122', 'nama_biro' => 'Subbagian Protokol', 'kode_deputi' => '212', 'created_at' => NULL,],
            ['kode_biro' => '2221', 'nama_biro' => 'Subbagian Tata Usaha Dewan', 'kode_deputi' => '222', 'created_at' => NULL,],
            ['kode_biro' => '2222', 'nama_biro' => 'Subbagian Tata Usaha Direktur Eksekutif', 'kode_deputi' => '222', 'created_at' => NULL,],
            ['kode_biro' => '2223', 'nama_biro' => 'Subbagian Protokol', 'kode_deputi' => '222', 'created_at' => NULL,],
            ['kode_biro' => '2321', 'nama_biro' => 'Subbagian Tata Usaha', 'kode_deputi' => '232', 'created_at' => NULL,],
            ['kode_biro' => '2322', 'nama_biro' => 'Subbagian Protokol', 'kode_deputi' => '232', 'created_at' => NULL,],
            ['kode_biro' => '4011', 'nama_biro' => 'Divisi Anggaran dan Perencanaan', 'kode_deputi' => '401', 'created_at' => NULL,],
            ['kode_biro' => '4012', 'nama_biro' => 'Divisi Perbendaharaan', 'kode_deputi' => '401', 'created_at' => NULL,],
            ['kode_biro' => '4013', 'nama_biro' => 'Divisi Akuntansi', 'kode_deputi' => '401', 'created_at' => NULL,],
            ['kode_biro' => '4021', 'nama_biro' => 'Divisi Pengembangan Usaha', 'kode_deputi' => '402', 'created_at' => NULL,],
            ['kode_biro' => '4022', 'nama_biro' => 'Divisi Pemasaran dan Penjualan', 'kode_deputi' => '402', 'created_at' => NULL,],
            ['kode_biro' => '4023', 'nama_biro' => 'Divisi Pembangunan dan Pemeliharaan', 'kode_deputi' => '402', 'created_at' => NULL,],
            ['kode_biro' => '4031', 'nama_biro' => 'Divisi Humas, Hukum dan Administrasi', 'kode_deputi' => '403', 'created_at' => NULL,],
            ['kode_biro' => '4032', 'nama_biro' => 'Divisi Sumber Daya Manusia dan Kerumahtanggaan', 'kode_deputi' => '403', 'created_at' => NULL,],
            ['kode_biro' => '5000', 'nama_biro' => 'Divisi Pengembangan Usaha', 'kode_deputi' => '500', 'created_at' => NULL,],
            ['kode_biro' => '5001', 'nama_biro' => 'Divisi Hukum dan Hubungan Masyarakat', 'kode_deputi' => '500', 'created_at' => NULL,],
            ['kode_biro' => '5002', 'nama_biro' => 'Divisi Pengamanan dan Bina Lingkungan', 'kode_deputi' => '500', 'created_at' => NULL,],
            ['kode_biro' => '5010', 'nama_biro' => 'Divisi Keuangan', 'kode_deputi' => '501', 'created_at' => NULL,],
            ['kode_biro' => '5011', 'nama_biro' => 'Divisi Administrasi', 'kode_deputi' => '501', 'created_at' => NULL,],
            ['kode_biro' => '5012', 'nama_biro' => 'Divisi Manajemen Aset', 'kode_deputi' => '501', 'created_at' => NULL,],
            ['kode_biro' => '5020', 'nama_biro' => 'Divisi Perencanaan dan Evaluasi', 'kode_deputi' => '502', 'created_at' => NULL,],
            ['kode_biro' => '5021', 'nama_biro' => 'Divisi Pembangunan dan Pengawasan', 'kode_deputi' => '502', 'created_at' => NULL,],
            ['kode_biro' => '5022', 'nama_biro' => 'Divisi Penataan dan Pemeliharaan', 'kode_deputi' => '502', 'created_at' => NULL,],
            ['kode_biro' => '5030', 'nama_biro' => 'Tata Usaha Satuan Pengawas Intern', 'kode_deputi' => '503', 'created_at' => NULL,],
            ['kode_biro' => '5211', 'nama_biro' => 'Divisi Keuangan', 'kode_deputi' => '521', 'created_at' => NULL,],
            ['kode_biro' => '5212', 'nama_biro' => 'Divisi Manajemen Aset dan Sistem Informasi', 'kode_deputi' => '521', 'created_at' => NULL,],
            ['kode_biro' => '5213', 'nama_biro' => 'Divisi Administrasi Umum', 'kode_deputi' => '521', 'created_at' => NULL,],
            ['kode_biro' => '5221', 'nama_biro' => 'Divisi Perencanaan', 'kode_deputi' => '522', 'created_at' => NULL,],
            ['kode_biro' => '5222', 'nama_biro' => 'Divisi Manajemen Pemeliharaan Lingkungan', 'kode_deputi' => '522', 'created_at' => NULL,],
            ['kode_biro' => '5223', 'nama_biro' => 'Divisi Pembangunan Proyek', 'kode_deputi' => '522', 'created_at' => NULL,],
            ['kode_biro' => '5231', 'nama_biro' => 'Divisi Hukum dan Pengamanan', 'kode_deputi' => '523', 'created_at' => NULL,],
            ['kode_biro' => '5232', 'nama_biro' => 'Divisi Pemasaran dan Humas', 'kode_deputi' => '523', 'created_at' => NULL,],
            ['kode_biro' => '5233', 'nama_biro' => 'Divisi Pengembangan Usaha', 'kode_deputi' => '523', 'created_at' => NULL,],
            ['kode_biro' => '6700', 'nama_biro' => 'Bagian Perlengkapan Rumah Tangga dan Layanan Pengadaan', 'kode_deputi' => '156', 'created_at' => NULL,],
            ['kode_biro' => 'X0010', 'nama_biro' => 'Biro Administrasi', 'kode_deputi' => 'X001', 'created_at' => NULL,],
            ['kode_biro' => 'X0011', 'nama_biro' => 'Biro Umum', 'kode_deputi' => 'X001', 'created_at' => NULL,],
            ['kode_biro' => 'X0012', 'nama_biro' => 'Biro Pengelolaan Istana', 'kode_deputi' => 'X001', 'created_at' => NULL,],
            ['kode_biro' => 'X0013', 'nama_biro' => 'Biro Pelayanan Kerumahtanggaan', 'kode_deputi' => 'X001', 'created_at' => NULL,],
            ['kode_biro' => 'X0020', 'nama_biro' => 'Biro Protokol', 'kode_deputi' => 'X002', 'created_at' => NULL,],
            ['kode_biro' => 'X0021', 'nama_biro' => 'Biro Pers, Media, dan Informasi', 'kode_deputi' => 'X002', 'created_at' => NULL,],
            ['kode_biro' => 'X0022', 'nama_biro' => 'Biro Dokumentasi dan Pelayanan Informasi Pers dan Media', 'kode_deputi' => 'X002', 'created_at' => NULL,],
            ['kode_biro' => 'X0030', 'nama_biro' => 'Subbagian Tata Usaha', 'kode_deputi' => 'X003', 'created_at' => NULL,],
            ['kode_biro' => 'X0031', 'nama_biro' => 'Subbagian Rumah Tangga dan Protokol', 'kode_deputi' => 'X003', 'created_at' => NULL,],
            ['kode_biro' => 'X0032', 'nama_biro' => 'Subbagian Bangunan', 'kode_deputi' => 'X003', 'created_at' => NULL,],
            ['kode_biro' => 'X0033', 'nama_biro' => 'Subbagian Perlengkapan', 'kode_deputi' => 'X003', 'created_at' => NULL,],
            ['kode_biro' => 'X0040', 'nama_biro' => 'Subbagian Tata Usaha', 'kode_deputi' => 'X004', 'created_at' => NULL,],
            ['kode_biro' => 'X0041', 'nama_biro' => 'Subbagian Rumah Tangga dan Protokol', 'kode_deputi' => 'X004', 'created_at' => NULL,],
            ['kode_biro' => 'X0042', 'nama_biro' => 'Subbagian Bangunan', 'kode_deputi' => 'X004', 'created_at' => NULL,],
            ['kode_biro' => 'X0043', 'nama_biro' => 'Subbagian Perlengkapan', 'kode_deputi' => 'X004', 'created_at' => NULL,],
            ['kode_biro' => 'X0050', 'nama_biro' => 'Subbagian Tata Usaha', 'kode_deputi' => 'X005', 'created_at' => NULL,],
            ['kode_biro' => 'X0051', 'nama_biro' => 'Subbagian Rumah Tangga dan Protokol', 'kode_deputi' => 'X005', 'created_at' => NULL,],
            ['kode_biro' => 'X0052', 'nama_biro' => 'Subbagian Bangunan', 'kode_deputi' => 'X005', 'created_at' => NULL,],
            ['kode_biro' => 'X0053', 'nama_biro' => 'Subbagian Perlengkapan', 'kode_deputi' => 'X005', 'created_at' => NULL,],
            ['kode_biro' => 'X0060', 'nama_biro' => 'Subbagian Tata Usaha', 'kode_deputi' => 'X006', 'created_at' => NULL,],
            ['kode_biro' => 'X0061', 'nama_biro' => 'Subbagian Rumah Tangga dan Protokol', 'kode_deputi' => 'X006', 'created_at' => NULL,],
            ['kode_biro' => 'X0062', 'nama_biro' => 'Subbagian Bangunan', 'kode_deputi' => 'X006', 'created_at' => NULL,],
            ['kode_biro' => 'X0063', 'nama_biro' => 'Subbagian Perlengkapan', 'kode_deputi' => 'X006', 'created_at' => NULL,],
            ['kode_biro' => 'X0100', 'nama_biro' => 'Asisten Deputi Hubungan Internasional', 'kode_deputi' => 'X010', 'created_at' => NULL,],
            ['kode_biro' => 'X0101', 'nama_biro' => 'Asisten Deputi Pemerintahan dan Politik Dalam Negeri', 'kode_deputi' => 'X010', 'created_at' => NULL,],
            ['kode_biro' => 'X0102', 'nama_biro' => 'Asisten Deputi Hukum dan Hak Asasi Manusia', 'kode_deputi' => 'X010', 'created_at' => NULL,],
            ['kode_biro' => 'X0103', 'nama_biro' => 'Asisten Deputi Komunikasi Politik', 'kode_deputi' => 'X010', 'created_at' => NULL,],
            ['kode_biro' => 'X0104', 'nama_biro' => 'Asisten Deputi Dokumentasi dan Diseminasi Informasi', 'kode_deputi' => 'X010', 'created_at' => NULL,],
            ['kode_biro' => 'X0110', 'nama_biro' => 'Asisten Deputi Program Ekonomi Khusus', 'kode_deputi' => 'X011', 'created_at' => NULL,],
            ['kode_biro' => 'X0111', 'nama_biro' => 'Asisten Deputi Perdagangan dan Pariwisata', 'kode_deputi' => 'X011', 'created_at' => NULL,],
            ['kode_biro' => 'X0112', 'nama_biro' => 'Asisten Deputi Industri dan Sumber Daya Alam', 'kode_deputi' => 'X011', 'created_at' => NULL,],
            ['kode_biro' => 'X0113', 'nama_biro' => 'Asisten Deputi Infrastruktur dan Energi', 'kode_deputi' => 'X011', 'created_at' => NULL,],
            ['kode_biro' => 'X0120', 'nama_biro' => 'Asisten Deputi  Kesejahteraan Rakyat Berbasis Keluarga', 'kode_deputi' => 'X012', 'created_at' => NULL,],
            ['kode_biro' => 'X0121', 'nama_biro' => 'Asisten Deputi  Kesejahteraan Rakyat Berbasis Komunitas', 'kode_deputi' => 'X012', 'created_at' => NULL,],
            ['kode_biro' => 'X0122', 'nama_biro' => 'Asisten Deputi  Kesejahteraan Rakyat Berbasis Usaha', 'kode_deputi' => 'X012', 'created_at' => NULL,],
            ['kode_biro' => 'X0123', 'nama_biro' => 'Biro Pemberdayaan Perempuan, Usaha Micro, Kecil dan Ketenaga Kerjaan', 'kode_deputi' => 'X012', 'created_at' => NULL,],
            ['kode_biro' => 'X0130', 'nama_biro' => 'Asisten Deputi Reformasi Birokrasi', 'kode_deputi' => 'X013', 'created_at' => NULL,],
            ['kode_biro' => 'X0131', 'nama_biro' => 'Asisten Deputi Pengawasan Intern Pemerintah', 'kode_deputi' => 'X013', 'created_at' => NULL,],
            ['kode_biro' => 'X0132', 'nama_biro' => 'Asisten Deputi Pelayanan Publik', 'kode_deputi' => 'X013', 'created_at' => NULL,],
            ['kode_biro' => 'X0133', 'nama_biro' => 'Biro Pengelolaan Data dan Pengaduan Masyarakat', 'kode_deputi' => 'X013', 'created_at' => NULL,],
            ['kode_biro' => 'X0140', 'nama_biro' => 'Biro Perencanaan dan Keuangan', 'kode_deputi' => 'X014', 'created_at' => NULL,],
            ['kode_biro' => 'X0141', 'nama_biro' => 'Biro Tata Usaha dan Kepegawaian', 'kode_deputi' => 'X014', 'created_at' => NULL,],
            ['kode_biro' => 'X0142', 'nama_biro' => 'Biro Protokol dan Kerumahtanggaan', 'kode_deputi' => 'X014', 'created_at' => NULL,],
            ['kode_biro' => 'X0143', 'nama_biro' => 'Biro Umum', 'kode_deputi' => 'X014', 'created_at' => NULL,],
            ['kode_biro' => 'X0144', 'nama_biro' => 'Biro Perlengkapan dan Kerumahtanggaan', 'kode_deputi' => 'X014', 'created_at' => NULL,],
            ['kode_biro' => 'X0150', 'nama_biro' => 'Bidang Penyiapan Naskah', 'kode_deputi' => 'X015', 'created_at' => NULL,],
            ['kode_biro' => 'X0151', 'nama_biro' => 'Bidang Penerjemahan', 'kode_deputi' => 'X015', 'created_at' => NULL,],
            ['kode_biro' => 'X0200', 'nama_biro' => 'Bagian Administrasi Pengangkatan', 'kode_deputi' => 'X020', 'created_at' => NULL,],
            ['kode_biro' => 'X0201', 'nama_biro' => 'Bagian Administrasi Pemberhentian', 'kode_deputi' => 'X020', 'created_at' => NULL,],
            ['kode_biro' => 'X0202', 'nama_biro' => 'Bagian Administrasi dan Pembinaan Personel Tni dan Polri', 'kode_deputi' => 'X020', 'created_at' => NULL,],
            ['kode_biro' => 'X0210', 'nama_biro' => 'Bagian Operasi Pengamanan', 'kode_deputi' => 'X021', 'created_at' => NULL,],
            ['kode_biro' => 'X0211', 'nama_biro' => 'Bagian Penyelidikan dan Pengamanan Khusus', 'kode_deputi' => 'X021', 'created_at' => NULL,],
            ['kode_biro' => 'X0212', 'nama_biro' => 'Bagian Administrasi Pengamanan', 'kode_deputi' => 'X021', 'created_at' => NULL,],
            ['kode_biro' => 'X0220', 'nama_biro' => 'Bagian Administrasi', 'kode_deputi' => 'X022', 'created_at' => NULL,],
            ['kode_biro' => 'X0221', 'nama_biro' => 'Bagian Verifikasi Gelar, Tanda Jasa, dan Tanda Kehormatan', 'kode_deputi' => 'X022', 'created_at' => NULL,],
            ['kode_biro' => 'X0222', 'nama_biro' => 'Bagian Penganugerahan', 'kode_deputi' => 'X022', 'created_at' => NULL,],
            ['kode_biro' => 'X0230', 'nama_biro' => 'Kelompok Jabatan Fungsional', 'kode_deputi' => 'X023', 'created_at' => NULL,],
            ['kode_biro' => 'X0231', 'nama_biro' => 'Bagian Perencanaan dan Evaluasi', 'kode_deputi' => 'X023', 'created_at' => NULL,],
            ['kode_biro' => 'X0232', 'nama_biro' => 'Bagian Kepegawaian dan Keuangan', 'kode_deputi' => 'X023', 'created_at' => NULL,],
            ['kode_biro' => 'X0233', 'nama_biro' => 'Bagian Tata Usaha dan Perlengkapan', 'kode_deputi' => 'X023', 'created_at' => NULL,],
            ['kode_biro' => 'X0240', 'nama_biro' => 'Ajudan Presiden', 'kode_deputi' => 'X024', 'created_at' => NULL,],
            ['kode_biro' => 'X0241', 'nama_biro' => 'Ajudan Wakil Presiden', 'kode_deputi' => 'X024', 'created_at' => NULL,],
            ['kode_biro' => 'X0242', 'nama_biro' => 'Bagian Penelitian dan Dokumentasi', 'kode_deputi' => 'X024', 'created_at' => NULL,],
            ['kode_biro' => 'X0243', 'nama_biro' => 'Ajudan Isteri Presiden', 'kode_deputi' => 'X024', 'created_at' => NULL,],
            ['kode_biro' => 'X0244', 'nama_biro' => 'Ajudan Isteri Wakil Presiden', 'kode_deputi' => 'X024', 'created_at' => NULL,],
            ['kode_biro' => 'X0250', 'nama_biro' => 'Petugas Kawal', 'kode_deputi' => 'X025', 'created_at' => NULL,],
            ['kode_biro' => 'X0251', 'nama_biro' => 'Bagian Penyelidik dan Pengamanan', 'kode_deputi' => 'X025', 'created_at' => NULL,],
            ['kode_biro' => 'X0252', 'nama_biro' => 'Bagian Administrasi dan Pengamanan', 'kode_deputi' => 'X025', 'created_at' => NULL,],
            ['kode_biro' => 'X0260', 'nama_biro' => 'Koordinator Dokter Pribadi Presiden ', 'kode_deputi' => 'X026', 'created_at' => NULL,],
            ['kode_biro' => 'X0261', 'nama_biro' => 'Dokter Pribadi Presiden', 'kode_deputi' => 'X026', 'created_at' => NULL,],
            ['kode_biro' => 'X0262', 'nama_biro' => 'Dokter Pribadi Wakil Presiden', 'kode_deputi' => 'X026', 'created_at' => NULL,],
            ['kode_biro' => 'X0270', 'nama_biro' => 'Koordinator Pemandu Wisata Istana', 'kode_deputi' => 'X027', 'created_at' => NULL,],
            ['kode_biro' => 'X0271', 'nama_biro' => 'Pemandu Wisata Istana', 'kode_deputi' => 'X027', 'created_at' => NULL,],
            ['kode_biro' => 'X0272', 'nama_biro' => 'Bagian Tata Usaha dan Perlengkapan', 'kode_deputi' => 'X027', 'created_at' => NULL,],
            ['kode_biro' => 'X0280', 'nama_biro' => 'Ajudan Presiden', 'kode_deputi' => 'X028', 'created_at' => NULL,],
            ['kode_biro' => 'X0281', 'nama_biro' => 'Ajudan Wakil Presiden', 'kode_deputi' => 'X028', 'created_at' => NULL,],
            ['kode_biro' => 'X0282', 'nama_biro' => 'Ajudan Isteri Presiden', 'kode_deputi' => 'X028', 'created_at' => NULL,],
            ['kode_biro' => 'X0283', 'nama_biro' => 'Ajudan Isteri Wakil Presiden', 'kode_deputi' => 'X028', 'created_at' => NULL,],
            ['kode_biro' => 'X0290', 'nama_biro' => 'Koordinator Dokter Presiden dan Wakil Presiden/Dokter Pribadi Presiden/Anggota', 'kode_deputi' => 'X029', 'created_at' => NULL,],
            ['kode_biro' => 'X0291', 'nama_biro' => 'Dokter Pribadi Presiden/Anggota', 'kode_deputi' => 'X029', 'created_at' => NULL,],
            ['kode_biro' => 'X0292', 'nama_biro' => 'Dokter Pribadi Wakil Presiden/Anggota', 'kode_deputi' => 'X029', 'created_at' => NULL,],
            ['kode_biro' => 'X0300', 'nama_biro' => 'Bagian Program dan Anggaran I', 'kode_deputi' => 'X030', 'created_at' => NULL,],
            ['kode_biro' => 'X0301', 'nama_biro' => 'Bagian Program dan Anggaran II', 'kode_deputi' => 'X030', 'created_at' => NULL,],
            ['kode_biro' => 'X0302', 'nama_biro' => 'Bagian Program dan Anggaran III', 'kode_deputi' => 'X030', 'created_at' => NULL,],
            ['kode_biro' => 'X0303', 'nama_biro' => 'Bagian Pemantauan dan Evaluasi', 'kode_deputi' => 'X030', 'created_at' => NULL,],
            ['kode_biro' => 'X0304', 'nama_biro' => 'Kelompok Jabatan Fungsional', 'kode_deputi' => 'X030', 'created_at' => NULL,],
            ['kode_biro' => 'X0310', 'nama_biro' => 'Bagian Pelaksanaan Anggaran I', 'kode_deputi' => 'X031', 'created_at' => NULL,],
            ['kode_biro' => 'X0311', 'nama_biro' => 'Bagian Pelaksanaan Anggaran II', 'kode_deputi' => 'X031', 'created_at' => NULL,],
            ['kode_biro' => 'X0312', 'nama_biro' => 'Bagian Akuntansi dan Pelaporan Keuangan', 'kode_deputi' => 'X031', 'created_at' => NULL,],
            ['kode_biro' => 'X0313', 'nama_biro' => 'Bagian Dukungan Administrasi Pelaksanaan Anggaran', 'kode_deputi' => 'X031', 'created_at' => NULL,],
            ['kode_biro' => 'X0314', 'nama_biro' => 'Bendahara', 'kode_deputi' => 'X031', 'created_at' => NULL,],
            ['kode_biro' => 'X0320', 'nama_biro' => 'Kelompok Jabatan Fungsional', 'kode_deputi' => 'X032', 'created_at' => NULL,],
            ['kode_biro' => 'X0321', 'nama_biro' => 'Bagian Persuratan dan Reproduksi', 'kode_deputi' => 'X032', 'created_at' => NULL,],
            ['kode_biro' => 'X0322', 'nama_biro' => 'Bagian Arsip', 'kode_deputi' => 'X032', 'created_at' => NULL,],
            ['kode_biro' => 'X0323', 'nama_biro' => 'Bagian Keprotokolan dan Tata Usaha Pimpinan', 'kode_deputi' => 'X032', 'created_at' => NULL,],
            ['kode_biro' => 'X0324', 'nama_biro' => 'Bagian Hubungan Masyarakat', 'kode_deputi' => 'X032', 'created_at' => NULL,],
            ['kode_biro' => 'X0330', 'nama_biro' => 'Bagian Kerja Sama Teknik Bilateral', 'kode_deputi' => 'X033', 'created_at' => NULL,],
            ['kode_biro' => 'X0331', 'nama_biro' => 'Bagian Kerja Sama Teknik Multilateral', 'kode_deputi' => 'X033', 'created_at' => NULL,],
            ['kode_biro' => 'X0332', 'nama_biro' => 'Bagian Kerja Sama Teknik Selatan-Selatan', 'kode_deputi' => 'X033', 'created_at' => NULL,],
            ['kode_biro' => 'X0333', 'nama_biro' => 'Bagian Kerja Sama Teknik Kebudayaan dan Organisasi Internasional Non Pemerintah', 'kode_deputi' => 'X033', 'created_at' => NULL,],
            ['kode_biro' => 'X0334', 'nama_biro' => 'Bagian Perjalanan dan Dukungan Kerja Sama Teknik', 'kode_deputi' => 'X033', 'created_at' => NULL,],
            ['kode_biro' => 'X0340', 'nama_biro' => 'Bagian Bangunan', 'kode_deputi' => 'X034', 'created_at' => NULL,],
            ['kode_biro' => 'X0341', 'nama_biro' => 'Bagian Perlengkapan dan Rumah Tangga', 'kode_deputi' => 'X034', 'created_at' => NULL,],
            ['kode_biro' => 'X0342', 'nama_biro' => 'Bagian Kendaraan', 'kode_deputi' => 'X034', 'created_at' => NULL,],
            ['kode_biro' => 'X0343', 'nama_biro' => 'Bagian Pengelolaan Barang Milik Negara', 'kode_deputi' => 'X034', 'created_at' => NULL,],
            ['kode_biro' => 'X0344', 'nama_biro' => 'Bagian Pelayanan Kesehatan', 'kode_deputi' => 'X034', 'created_at' => NULL,],
            ['kode_biro' => 'X0345', 'nama_biro' => 'Bagian Keamanan Dalam', 'kode_deputi' => 'X034', 'created_at' => NULL,],
            ['kode_biro' => 'X0346', 'nama_biro' => 'Kelompok Jabatan Fungsional Tertentu', 'kode_deputi' => 'X034', 'created_at' => NULL,],
            ['kode_biro' => 'X0350', 'nama_biro' => 'Bagian Bangunan', 'kode_deputi' => 'X035', 'created_at' => NULL,],
            ['kode_biro' => 'X0351', 'nama_biro' => 'Bagian Perlengkapan', 'kode_deputi' => 'X035', 'created_at' => NULL,],
            ['kode_biro' => 'X0352', 'nama_biro' => 'Bagian Kendaraan', 'kode_deputi' => 'X035', 'created_at' => NULL,],
            ['kode_biro' => 'X0353', 'nama_biro' => 'Bagian Penata Usahaan Aset', 'kode_deputi' => 'X035', 'created_at' => NULL,],
            ['kode_biro' => 'X0354', 'nama_biro' => 'Unit Kesehatan', 'kode_deputi' => 'X035', 'created_at' => NULL,],
            ['kode_biro' => 'X0355', 'nama_biro' => 'Unit Keamanan Dalam', 'kode_deputi' => 'X035', 'created_at' => NULL,],
            ['kode_biro' => 'X0360', 'nama_biro' => 'Lain-lain', 'kode_deputi' => 'X036', 'created_at' => NULL,],
            ['kode_biro' => 'X0400', 'nama_biro' => 'Bidang Politik, Hukum, dan Keamanan', 'kode_deputi' => 'X040', 'created_at' => NULL,],
            ['kode_biro' => 'X0401', 'nama_biro' => 'Bidang Perekonomian', 'kode_deputi' => 'X040', 'created_at' => NULL,],
            ['kode_biro' => 'X0402', 'nama_biro' => 'Bidang Kesejahteraan Rakyat', 'kode_deputi' => 'X040', 'created_at' => NULL,],
            ['kode_biro' => 'X0403', 'nama_biro' => 'Arsiparis', 'kode_deputi' => 'X040', 'created_at' => NULL,],
            ['kode_biro' => 'X0410', 'nama_biro' => 'Bidang Hubungan Bilateral', 'kode_deputi' => 'X041', 'created_at' => NULL,],
            ['kode_biro' => 'X0411', 'nama_biro' => 'Bidang Hubungan Regional', 'kode_deputi' => 'X041', 'created_at' => NULL,],
            ['kode_biro' => 'X0412', 'nama_biro' => 'Bidang Hubungan Multilateral Perserikatan Bangsa-Bangsa', 'kode_deputi' => 'X041', 'created_at' => NULL,],
            ['kode_biro' => 'X0413', 'nama_biro' => 'Bagian Pertahanan dan Keamanan', 'kode_deputi' => 'X041', 'created_at' => NULL,],
            ['kode_biro' => 'X0420', 'nama_biro' => 'Bidang Naskah', 'kode_deputi' => 'X042', 'created_at' => NULL,],
            ['kode_biro' => 'X0421', 'nama_biro' => 'Bidang Penerjemahan', 'kode_deputi' => 'X042', 'created_at' => NULL,],
            ['kode_biro' => 'X0422', 'nama_biro' => 'Bidang Verbatim', 'kode_deputi' => 'X042', 'created_at' => NULL,],
            ['kode_biro' => 'X0423', 'nama_biro' => 'Bidang Pengelolaan dan Pengembangan Jabatan Fungsional Penerjemah', 'kode_deputi' => 'X042', 'created_at' => NULL,],
            ['kode_biro' => 'X0424', 'nama_biro' => 'Kelompok Jabatan Fungsional', 'kode_deputi' => 'X042', 'created_at' => NULL,],
            ['kode_biro' => 'X0430', 'nama_biro' => 'Kelompok Jabatan Fungsional', 'kode_deputi' => 'X043', 'created_at' => NULL,],
            ['kode_biro' => 'X0431', 'nama_biro' => 'Bidang Pengembangan Sistem dan Jaringan', 'kode_deputi' => 'X043', 'created_at' => NULL,],
            ['kode_biro' => 'X0432', 'nama_biro' => 'Bidang Informasi dan Basis Data Kebijakan', 'kode_deputi' => 'X043', 'created_at' => NULL,],
            ['kode_biro' => 'X0433', 'nama_biro' => 'Bidang Perpustakaan', 'kode_deputi' => 'X043', 'created_at' => NULL,],
            ['kode_biro' => 'X0440', 'nama_biro' => 'Bagian Pengembangan dan Penerapan Sistem', 'kode_deputi' => 'X044', 'created_at' => NULL,],
            ['kode_biro' => 'X0441', 'nama_biro' => 'Bagian Jaringan dan Multimedia', 'kode_deputi' => 'X044', 'created_at' => NULL,],
            ['kode_biro' => 'X0442', 'nama_biro' => 'Bagian Basis Data Kebijakan', 'kode_deputi' => 'X044', 'created_at' => NULL,],
            ['kode_biro' => 'X0443', 'nama_biro' => 'Bagian Perputakaan', 'kode_deputi' => 'X044', 'created_at' => NULL,],
            ['kode_biro' => 'X0500', 'nama_biro' => 'Bagian Pengangkatan, Pemberhentian, dan Pensiun Pejabat Negara', 'kode_deputi' => 'X050', 'created_at' => NULL,],
            ['kode_biro' => 'X0501', 'nama_biro' => 'Bagian Informasi Pejabat Negara', 'kode_deputi' => 'X050', 'created_at' => NULL,],
            ['kode_biro' => 'X0510', 'nama_biro' => 'Kelompok Jabatan Fungsional', 'kode_deputi' => 'X051', 'created_at' => NULL,],
            ['kode_biro' => 'X0511', 'nama_biro' => 'Bagian Perencanaan dan Informasi Kepegawaian', 'kode_deputi' => 'X051', 'created_at' => NULL,],
            ['kode_biro' => 'X0512', 'nama_biro' => 'Bagian Mutasi Kepegawaian', 'kode_deputi' => 'X051', 'created_at' => NULL,],
            ['kode_biro' => 'X0513', 'nama_biro' => 'Bagian  Disiplin, Kesejahteraan, dan Tata Usaha Kepegawaian', 'kode_deputi' => 'X051', 'created_at' => NULL,],
            ['kode_biro' => 'X0514', 'nama_biro' => 'Unit Koperasi', 'kode_deputi' => 'X051', 'created_at' => NULL,],
            ['kode_biro' => 'X0515', 'nama_biro' => 'Unit KORPRI', 'kode_deputi' => 'X051', 'created_at' => NULL,],
            ['kode_biro' => 'X0516', 'nama_biro' => 'Non Job', 'kode_deputi' => 'X051', 'created_at' => NULL,],
            ['kode_biro' => 'X0517', 'nama_biro' => 'Tugas Belajar Luar Negeri', 'kode_deputi' => 'X051', 'created_at' => NULL,],
            ['kode_biro' => 'X0520', 'nama_biro' => 'Bagian Organisasi', 'kode_deputi' => 'X052', 'created_at' => NULL,],
            ['kode_biro' => 'X0521', 'nama_biro' => 'Bagian Tata Laksana', 'kode_deputi' => 'X052', 'created_at' => NULL,],
            ['kode_biro' => 'X0522', 'nama_biro' => 'Bagian Akuntabilitas Kinerja I', 'kode_deputi' => 'X052', 'created_at' => NULL,],
            ['kode_biro' => 'X0523', 'nama_biro' => 'Bagian Akuntabilitas Kinerja II', 'kode_deputi' => 'X052', 'created_at' => NULL,],
            ['kode_biro' => 'X0530', 'nama_biro' => 'Bidang Diklat Struktural', 'kode_deputi' => 'X053', 'created_at' => NULL,],
            ['kode_biro' => 'X0531', 'nama_biro' => 'Bidang Diklat Fungsional', 'kode_deputi' => 'X053', 'created_at' => NULL,],
            ['kode_biro' => 'X0532', 'nama_biro' => 'Bidang Diklat Teknis', 'kode_deputi' => 'X053', 'created_at' => NULL,],
            ['kode_biro' => 'X0533', 'nama_biro' => 'Bagian Tata Usaha', 'kode_deputi' => 'X053', 'created_at' => NULL,],
            ['kode_biro' => 'X0534', 'nama_biro' => 'Widyaiswara', 'kode_deputi' => 'X053', 'created_at' => NULL,],
            ['kode_biro' => 'X0600', 'nama_biro' => 'Bidang Hubungan MPR, DPR, dan DPD', 'kode_deputi' => 'X060', 'created_at' => NULL,],
            ['kode_biro' => 'X0601', 'nama_biro' => 'Bidang Hubungan MA, MK, KY, BPK, dan BI', 'kode_deputi' => 'X060', 'created_at' => NULL,],
            ['kode_biro' => 'X0602', 'nama_biro' => 'Bidang Hubungan Lembaga Non Struktural', 'kode_deputi' => 'X060', 'created_at' => NULL,],
            ['kode_biro' => 'X0603', 'nama_biro' => 'Kelompok Jabatan Fungsional Tertentu', 'kode_deputi' => 'X060', 'created_at' => NULL,],
            ['kode_biro' => 'X0610', 'nama_biro' => 'Bidang Hubungan Lembaga Daerah Wilayah I', 'kode_deputi' => 'X061', 'created_at' => NULL,],
            ['kode_biro' => 'X0611', 'nama_biro' => 'Bidang Hubungan Lembaga Daerah Wilayah Ii', 'kode_deputi' => 'X061', 'created_at' => NULL,],
            ['kode_biro' => 'X0612', 'nama_biro' => 'Bidang Hubungan Lembaga Daerah Wilayah Iii', 'kode_deputi' => 'X061', 'created_at' => NULL,],
            ['kode_biro' => 'X0613', 'nama_biro' => 'Bidang Hubungan Organisasi Politik', 'kode_deputi' => 'X061', 'created_at' => NULL,],
            ['kode_biro' => 'X0614', 'nama_biro' => 'Arsiparis', 'kode_deputi' => 'X061', 'created_at' => NULL,],
            ['kode_biro' => 'X0620', 'nama_biro' => 'Bidang Hubungan Organisasi Kemasyarakatan Kesamaan Agama dan Fungsi', 'kode_deputi' => 'X062', 'created_at' => NULL,],
            ['kode_biro' => 'X0621', 'nama_biro' => 'Bidang Hubungan Organisasi Kemasyarakatan Kesamaan Kegiatan dan Profesi', 'kode_deputi' => 'X062', 'created_at' => NULL,],
            ['kode_biro' => 'X0622', 'nama_biro' => 'Bidang Hubungan Lembaga Swadaya Masyarakat Advokasi', 'kode_deputi' => 'X062', 'created_at' => NULL,],
            ['kode_biro' => 'X0623', 'nama_biro' => 'Bidang Hubungan Lembaga Swadaya Masyarakat Pemberdayaan', 'kode_deputi' => 'X062', 'created_at' => NULL,],
            ['kode_biro' => 'X0630', 'nama_biro' => 'Bidang Korupsi, Hukum dan Hak Asasi Manusia', 'kode_deputi' => 'X063', 'created_at' => NULL,],
            ['kode_biro' => 'X0631', 'nama_biro' => 'Bidang Aparatur, Ketenagakerjaan, dan Kewaspadaan Nasional', 'kode_deputi' => 'X063', 'created_at' => NULL,],
            ['kode_biro' => 'X0632', 'nama_biro' => 'Bidang Pertanahan, Perumahan, dan Lingkungan Hidup', 'kode_deputi' => 'X063', 'created_at' => NULL,],
            ['kode_biro' => 'X0633', 'nama_biro' => 'Arsiparis', 'kode_deputi' => 'X063', 'created_at' => NULL,],
            ['kode_biro' => 'X0640', 'nama_biro' => 'Bagian Hubungan Ormas Kesamaan Agama dan Fungsi', 'kode_deputi' => 'X064', 'created_at' => NULL,],
            ['kode_biro' => 'X0641', 'nama_biro' => 'Bagian Hubungan Ormas Kesamaan Kegiatan dan Profesi', 'kode_deputi' => 'X064', 'created_at' => NULL,],
            ['kode_biro' => 'X0700', 'nama_biro' => 'Bidang Moneter dan Jasa Keuangan', 'kode_deputi' => 'X070', 'created_at' => NULL,],
            ['kode_biro' => 'X0701', 'nama_biro' => 'Bidang Sumber Daya Alam dan Lingkungan Hidup', 'kode_deputi' => 'X070', 'created_at' => NULL,],
            ['kode_biro' => 'X0702', 'nama_biro' => 'Bidang Prasarana dan Tata Ruang', 'kode_deputi' => 'X070', 'created_at' => NULL,],
            ['kode_biro' => 'X0703', 'nama_biro' => 'Bidang Perindustrian, Perdagangan, dan Badan Usaha', 'kode_deputi' => 'X070', 'created_at' => NULL,],
            ['kode_biro' => 'X0710', 'nama_biro' => 'Bidang Politik dan Pemerintahan Daerah', 'kode_deputi' => 'X071', 'created_at' => NULL,],
            ['kode_biro' => 'X0711', 'nama_biro' => 'Bidang Pertahanan, Keamanan, Hukum, dan Hak Asasi Manusia', 'kode_deputi' => 'X071', 'created_at' => NULL,],
            ['kode_biro' => 'X0712', 'nama_biro' => 'Bidang Aparatur Negara', 'kode_deputi' => 'X071', 'created_at' => NULL,],
            ['kode_biro' => 'X0713', 'nama_biro' => 'Bidang Kesejahteraan Rakyat', 'kode_deputi' => 'X071', 'created_at' => NULL,],
            ['kode_biro' => 'X0720', 'nama_biro' => 'Bidang Litigasi dan Permasalahan Hukum', 'kode_deputi' => 'X072', 'created_at' => NULL,],
            ['kode_biro' => 'X0721', 'nama_biro' => 'Bidang Perjanjian Internasional', 'kode_deputi' => 'X072', 'created_at' => NULL,],
            ['kode_biro' => 'X0722', 'nama_biro' => 'Bidang Prerogatif dan Naturalisasi', 'kode_deputi' => 'X072', 'created_at' => NULL,],
            ['kode_biro' => 'X0723', 'nama_biro' => 'Bidang Distribusi, Publikasi, dan Dokumentasi', 'kode_deputi' => 'X072', 'created_at' => NULL,],
            ['kode_biro' => 'X0730', 'nama_biro' => 'Bagian Permasalahan Hukum', 'kode_deputi' => 'X073', 'created_at' => NULL,],
            ['kode_biro' => 'X0731', 'nama_biro' => 'Bagian Ratifikasi', 'kode_deputi' => 'X073', 'created_at' => NULL,],
            ['kode_biro' => 'X0732', 'nama_biro' => 'Bagian Prerogratif dan Naturalisasi', 'kode_deputi' => 'X073', 'created_at' => NULL,],
            ['kode_biro' => 'X0733', 'nama_biro' => 'Bagian Administrasi PUU', 'kode_deputi' => 'X073', 'created_at' => NULL,],
            ['kode_biro' => 'X0810', 'nama_biro' => 'Bagian Administrasi Pengawasan', 'kode_deputi' => 'X081', 'created_at' => NULL,],
            ['kode_biro' => 'X0811', 'nama_biro' => 'Auditor', 'kode_deputi' => 'X081', 'created_at' => NULL,],
            ['kode_biro' => 'X0820', 'nama_biro' => 'Bagian Pengembangan Sistem Akuntabilitas Kinerja', 'kode_deputi' => 'X082', 'created_at' => NULL,],
            ['kode_biro' => 'X0821', 'nama_biro' => 'Bagian Pemantauan Evaluasi Akuntabilitas Kinerja', 'kode_deputi' => 'X082', 'created_at' => NULL,],
            ['kode_biro' => 'X0822', 'nama_biro' => 'Bagian Pelaporan Akuntabilitas Kinerja', 'kode_deputi' => 'X082', 'created_at' => NULL,],
            ['kode_biro' => 'X0830', 'nama_biro' => 'Bagian Pengaduan Masyarakat Bidang Aparatur dan Ketenagakerjaan', 'kode_deputi' => 'X083', 'created_at' => NULL,],
            ['kode_biro' => 'X0831', 'nama_biro' => 'Bagian Pengaduan Masyarakat Bidang HAM, Pertanahan, dan Perumahan', 'kode_deputi' => 'X083', 'created_at' => NULL,],
            ['kode_biro' => 'X10', 'nama_biro' => 'Biro Administrasi', 'kode_deputi' => 'X001', 'created_at' => NULL,],
            ['kode_biro' => 'X1000', 'nama_biro' => 'Auditor', 'kode_deputi' => 'X100', 'created_at' => NULL,],
            ['kode_biro' => 'X1010', 'nama_biro' => 'Subbagian Tata Usaha', 'kode_deputi' => 'X101', 'created_at' => NULL,],
            ['kode_biro' => 'X1011', 'nama_biro' => 'Subbagian Administrasi Tindak Lanjut Hasil Pengawasan', 'kode_deputi' => 'X101', 'created_at' => NULL,],
            ['kode_biro' => 'X11', 'nama_biro' => 'Biro Umum', 'kode_deputi' => 'X001', 'created_at' => NULL,],
            ['kode_biro' => 'X1100', 'nama_biro' => 'Subbagian Perencanaan', 'kode_deputi' => 'X110', 'created_at' => NULL,],
            ['kode_biro' => 'X1101', 'nama_biro' => 'Subbagian Kerumahtanggaan', 'kode_deputi' => 'X110', 'created_at' => NULL,],
            ['kode_biro' => 'X1102', 'nama_biro' => 'Subbagian Umum', 'kode_deputi' => 'X110', 'created_at' => NULL,],
            ['kode_biro' => 'X1110', 'nama_biro' => 'Subbidang Penyusunan dan Evaluasi Program Diklat Struktural', 'kode_deputi' => 'X111', 'created_at' => NULL,],
            ['kode_biro' => 'X1111', 'nama_biro' => 'Subbidang Penyelenggaraan Diklat Struktural', 'kode_deputi' => 'X111', 'created_at' => NULL,],
            ['kode_biro' => 'X1120', 'nama_biro' => 'Subbidang Penyusunan dan Evaluasi Program Diklat Fungsional', 'kode_deputi' => 'X112', 'created_at' => NULL,],
            ['kode_biro' => 'X1121', 'nama_biro' => 'Subidang Penyelenggaraan Diklat Fungsional', 'kode_deputi' => 'X112', 'created_at' => NULL,],
            ['kode_biro' => 'X1130', 'nama_biro' => 'Subbidang Penyusunan dan Evaluasi Program Diklat Teknis', 'kode_deputi' => 'X113', 'created_at' => NULL,],
            ['kode_biro' => 'X1131', 'nama_biro' => 'Subbidang Penyelenggaraan Diklat Teknis', 'kode_deputi' => 'X113', 'created_at' => NULL,],
            ['kode_biro' => 'X12', 'nama_biro' => 'Biro Pengelolaan Istana', 'kode_deputi' => 'X001', 'created_at' => NULL,],
            ['kode_biro' => 'X1200', 'nama_biro' => 'Sekretaris Anggota DPP Bidang Ekonomi dan Lingkungan Hidup', 'kode_deputi' => 'X120', 'created_at' => NULL,],
            ['kode_biro' => 'X1201', 'nama_biro' => 'Sekretaris Anggota DPP Bidang Hubungan Antar Agama', 'kode_deputi' => 'X120', 'created_at' => NULL,],
            ['kode_biro' => 'X1202', 'nama_biro' => 'Sekretaris Anggota DPP Bidang Pendidikan dan Kebudayaan', 'kode_deputi' => 'X120', 'created_at' => NULL,],
            ['kode_biro' => 'X1203', 'nama_biro' => 'Sekretaris Anggota DPP Bidang Pembangunan dan Otonomi Daerah', 'kode_deputi' => 'X120', 'created_at' => NULL,],
            ['kode_biro' => 'X1204', 'nama_biro' => 'Sekretaris Anggota DPP Bidang Pertahanan dan Keamanan', 'kode_deputi' => 'X120', 'created_at' => NULL,],
            ['kode_biro' => 'X1205', 'nama_biro' => 'Sekretaris Anggota DPP Bidang Hukum dan Ketatanegaraan', 'kode_deputi' => 'X120', 'created_at' => NULL,],
            ['kode_biro' => 'X1206', 'nama_biro' => 'Sekretaris Anggota DPP Bidang Pemerintahan dan Reformasi Birokrasi', 'kode_deputi' => 'X120', 'created_at' => NULL,],
            ['kode_biro' => 'X1207', 'nama_biro' => 'Sekretaris Anggota DPP Bidang Kesejahteraan Rakyat', 'kode_deputi' => 'X120', 'created_at' => NULL,],
            ['kode_biro' => 'X1208', 'nama_biro' => 'Sekretaris Anggota DPP Bidang Hubungan Luar Negeri/Internasional', 'kode_deputi' => 'X120', 'created_at' => NULL,],
            ['kode_biro' => 'X1210', 'nama_biro' => 'Bagian Politik, Hukum, dan Keamanan Negara', 'kode_deputi' => 'X121', 'created_at' => NULL,],
            ['kode_biro' => 'X1211', 'nama_biro' => 'Bagian Perekonomian', 'kode_deputi' => 'X121', 'created_at' => NULL,],
            ['kode_biro' => 'X1212', 'nama_biro' => 'Bagian Kesejahteraan Rakyat', 'kode_deputi' => 'X121', 'created_at' => NULL,],
            ['kode_biro' => 'X1220', 'nama_biro' => 'Bagian Tata Usaha, Program dan Anggaran', 'kode_deputi' => 'X122', 'created_at' => NULL,],
            ['kode_biro' => 'X1221', 'nama_biro' => 'Bagian Keuangan', 'kode_deputi' => 'X122', 'created_at' => NULL,],
            ['kode_biro' => 'X1222', 'nama_biro' => 'Bagian Perlengkapan, Keprotokolan, dan Persidangan', 'kode_deputi' => 'X122', 'created_at' => NULL,],
            ['kode_biro' => 'X1300', 'nama_biro' => 'Pranata Komputer', 'kode_deputi' => 'X130', 'created_at' => NULL,],
            ['kode_biro' => 'X1301', 'nama_biro' => 'Sandiman', 'kode_deputi' => 'X130', 'created_at' => NULL,],
            ['kode_biro' => 'X1310', 'nama_biro' => 'Subbagian Perencanaan dan Pelaporan Kinerja', 'kode_deputi' => 'X131', 'created_at' => NULL,],
            ['kode_biro' => 'X1311', 'nama_biro' => 'Subbagian Kepegawain', 'kode_deputi' => 'X131', 'created_at' => NULL,],
            ['kode_biro' => 'X1320', 'nama_biro' => 'Subbagian Pengolahan dan Pengamanan Informasi dan Komunikasi', 'kode_deputi' => 'X132', 'created_at' => NULL,],
            ['kode_biro' => 'X1321', 'nama_biro' => 'Subbagian Pengembangan dan Pemeliharaan Sistem Informasi dan Jaringan Komunikasi', 'kode_deputi' => 'X132', 'created_at' => NULL,],
            ['kode_biro' => 'X1330', 'nama_biro' => 'Subbagian Keuangan', 'kode_deputi' => 'X133', 'created_at' => NULL,],
            ['kode_biro' => 'X1331', 'nama_biro' => 'Subbagian Tata Usaha', 'kode_deputi' => 'X133', 'created_at' => NULL,],
            ['kode_biro' => 'X1332', 'nama_biro' => 'Subbagian Perlengkapan dan Rumah Tangga', 'kode_deputi' => 'X133', 'created_at' => NULL,],
            ['kode_biro' => 'X1500', 'nama_biro' => 'Bagian Politik, Hukum, dan Keamanan Negara', 'kode_deputi' => 'X150', 'created_at' => NULL,],
            ['kode_biro' => 'X1501', 'nama_biro' => 'Bagian Perekonomian', 'kode_deputi' => 'X150', 'created_at' => NULL,],
            ['kode_biro' => 'X1502', 'nama_biro' => 'Bagian Kesejahteraan Rakyat', 'kode_deputi' => 'X150', 'created_at' => NULL,],
            ['kode_biro' => 'X1510', 'nama_biro' => 'Bagian Tata Usaha, Program dan Anggaran', 'kode_deputi' => 'X151', 'created_at' => NULL,],
            ['kode_biro' => 'X1511', 'nama_biro' => 'Bagian Keuangan', 'kode_deputi' => 'X151', 'created_at' => NULL,],
            ['kode_biro' => 'X1512', 'nama_biro' => 'Bagian Perlengkapan dan Persidangan', 'kode_deputi' => 'X151', 'created_at' => NULL,],
            ['kode_biro' => 'X1600', 'nama_biro' => 'Bagian Perencanaan dan Pengolahan Data', 'kode_deputi' => 'X160', 'created_at' => NULL,],
            ['kode_biro' => 'X1601', 'nama_biro' => 'Bagian Umum', 'kode_deputi' => 'X160', 'created_at' => NULL,],
            ['kode_biro' => 'X1602', 'nama_biro' => 'Bendahara', 'kode_deputi' => 'X160', 'created_at' => NULL,],
            ['kode_biro' => 'X20', 'nama_biro' => 'Biro Protokol', 'kode_deputi' => 'X002', 'created_at' => NULL,],
            ['kode_biro' => 'X21', 'nama_biro' => 'Biro Pers, Media, dan Informasi', 'kode_deputi' => 'X002', 'created_at' => NULL,],
            ['kode_biro' => 'X30', 'nama_biro' => 'Biro Administrasi', 'kode_deputi' => '000', 'created_at' => NULL,],
            ['kode_biro' => 'X31', 'nama_biro' => 'Biro Administrasi', 'kode_deputi' => '000', 'created_at' => NULL,],
            ['kode_biro' => 'X32', 'nama_biro' => 'Biro Administrasi', 'kode_deputi' => '000', 'created_at' => NULL,],
            ['kode_biro' => 'X33', 'nama_biro' => 'Biro Administrasi', 'kode_deputi' => '000', 'created_at' => NULL,],
            ['kode_biro' => 'X40', 'nama_biro' => 'Biro Administrasi', 'kode_deputi' => '000', 'created_at' => NULL,],
            ['kode_biro' => 'X4010', 'nama_biro' => 'Bagian Pemerintahan Umum dan Otonomi Daerah', 'kode_deputi' => 'X401', 'created_at' => NULL,],
            ['kode_biro' => 'X4011', 'nama_biro' => 'Bagian Kesatuan Bangsa dan Politik', 'kode_deputi' => 'X401', 'created_at' => NULL,],
            ['kode_biro' => 'X4012', 'nama_biro' => 'Bagian Hubungan Internasional', 'kode_deputi' => 'X401', 'created_at' => NULL,],
            ['kode_biro' => 'X4013', 'nama_biro' => 'Bagian Pertahanan dan Hak Asasi Manusia', 'kode_deputi' => 'X401', 'created_at' => NULL,],
            ['kode_biro' => 'X4020', 'nama_biro' => 'Bagian Pengentasan Kemiskinan', 'kode_deputi' => 'X402', 'created_at' => NULL,],
            ['kode_biro' => 'X4021', 'nama_biro' => 'Bagian Kependudukan', 'kode_deputi' => 'X402', 'created_at' => NULL,],
            ['kode_biro' => 'X4022', 'nama_biro' => 'Bagian Sosial dan Budaya', 'kode_deputi' => 'X402', 'created_at' => NULL,],
            ['kode_biro' => 'X4023', 'nama_biro' => 'Bagian Sumber Daya Manusia', 'kode_deputi' => 'X402', 'created_at' => NULL,],
            ['kode_biro' => 'X4030', 'nama_biro' => 'Bagian Moneter dan Lembaga Keuangan', 'kode_deputi' => 'X403', 'created_at' => NULL,],
            ['kode_biro' => 'X4031', 'nama_biro' => 'Bagian Fiskal', 'kode_deputi' => 'X403', 'created_at' => NULL,],
            ['kode_biro' => 'X4032', 'nama_biro' => 'Bagian Badan Usaha', 'kode_deputi' => 'X403', 'created_at' => NULL,],
            ['kode_biro' => 'X4040', 'nama_biro' => 'Bagian Industri', 'kode_deputi' => 'X404', 'created_at' => NULL,],
            ['kode_biro' => 'X4041', 'nama_biro' => 'Bagian Perdagangan', 'kode_deputi' => 'X404', 'created_at' => NULL,],
            ['kode_biro' => 'X4042', 'nama_biro' => 'Bagian Energi, Sumber Daya Alam, dan Lingkungan Hidup', 'kode_deputi' => 'X404', 'created_at' => NULL,],
            ['kode_biro' => 'X4043', 'nama_biro' => 'Bagian Infrastruktur', 'kode_deputi' => 'X404', 'created_at' => NULL,],
            ['kode_biro' => 'X41', 'nama_biro' => 'Biro Administrasi', 'kode_deputi' => '000', 'created_at' => NULL,],
            ['kode_biro' => 'X4100', 'nama_biro' => 'Bagian Perindustrian, Perdagangan, dan Badan Usaha', 'kode_deputi' => 'X410', 'created_at' => NULL,],
            ['kode_biro' => 'X4101', 'nama_biro' => 'Bagian Moneter dan Perbankan', 'kode_deputi' => 'X410', 'created_at' => NULL,],
            ['kode_biro' => 'X4102', 'nama_biro' => 'Bagian Prasarana dan Sumber Daya Alam', 'kode_deputi' => 'X410', 'created_at' => NULL,],
            ['kode_biro' => 'X4103', 'nama_biro' => 'Bagian Lingkungan Hidup dan Tata Ruang', 'kode_deputi' => 'X410', 'created_at' => NULL,],
            ['kode_biro' => 'X4104', 'nama_biro' => 'Bagian Anggaran Negara dan Jasa Konstruksi', 'kode_deputi' => 'X410', 'created_at' => NULL,],
            ['kode_biro' => 'X4110', 'nama_biro' => 'Bagian Politik, Keamanan, dan Kehakiman', 'kode_deputi' => 'X411', 'created_at' => NULL,],
            ['kode_biro' => 'X4111', 'nama_biro' => 'Bagian Pertanahan', 'kode_deputi' => 'X411', 'created_at' => NULL,],
            ['kode_biro' => 'X4112', 'nama_biro' => 'Bagian Ratifikasi', 'kode_deputi' => 'X411', 'created_at' => NULL,],
            ['kode_biro' => 'X4113', 'nama_biro' => 'Bagian Permasalahan Hukum Privat', 'kode_deputi' => 'X411', 'created_at' => NULL,],
            ['kode_biro' => 'X4114', 'nama_biro' => 'Bagian Permasalahan Hukum Publik', 'kode_deputi' => 'X411', 'created_at' => NULL,],
            ['kode_biro' => 'X4120', 'nama_biro' => 'Bagian Aparatur Negara', 'kode_deputi' => 'X412', 'created_at' => NULL,],
            ['kode_biro' => 'X4121', 'nama_biro' => 'Bagian Pemerintahan Daerah', 'kode_deputi' => 'X412', 'created_at' => NULL,],
            ['kode_biro' => 'X4122', 'nama_biro' => 'Bagian Pendidikan, Kesehatan, Budaya, Pariwisata, dan Agama', 'kode_deputi' => 'X412', 'created_at' => NULL,],
            ['kode_biro' => 'X4123', 'nama_biro' => 'Bagian Ketenagakerjaan, Kependudukan, dan Kesejahteraan Sosial', 'kode_deputi' => 'X412', 'created_at' => NULL,],
            ['kode_biro' => 'X4130', 'nama_biro' => 'Bagian Dokumentasi dan Distribusi', 'kode_deputi' => 'X413', 'created_at' => NULL,],
            ['kode_biro' => 'X4131', 'nama_biro' => 'Bagian Aplikasi dan Implementasi Sistem Informasi Peraturan Perundang-undangan', 'kode_deputi' => 'X413', 'created_at' => NULL,],
            ['kode_biro' => 'X4132', 'nama_biro' => 'Bagian Sistem dan Prasarana Sistem Informasi Peraturan Perundang-undangan', 'kode_deputi' => 'X413', 'created_at' => NULL,],
            ['kode_biro' => 'X42', 'nama_biro' => 'Biro Administrasi', 'kode_deputi' => '000', 'created_at' => NULL,],
            ['kode_biro' => 'X4200', 'nama_biro' => 'Bagian Penyiapan Sidang', 'kode_deputi' => 'X420', 'created_at' => NULL,],
            ['kode_biro' => 'X4201', 'nama_biro' => 'Bagian Peliputan Sidang', 'kode_deputi' => 'X420', 'created_at' => NULL,],
            ['kode_biro' => 'X4202', 'nama_biro' => 'Bagian Hubungan Kelembagaan', 'kode_deputi' => 'X420', 'created_at' => NULL,],
            ['kode_biro' => 'X4210', 'nama_biro' => 'Bagian Dokumentasi Sidang', 'kode_deputi' => 'X421', 'created_at' => NULL,],
            ['kode_biro' => 'X4211', 'nama_biro' => 'Bagian Pengolahan Data', 'kode_deputi' => 'X421', 'created_at' => NULL,],
            ['kode_biro' => 'X4212', 'nama_biro' => 'Bagian Pemantauan dan Evaluasi', 'kode_deputi' => 'X421', 'created_at' => NULL,],
            ['kode_biro' => 'X4220', 'nama_biro' => 'Bagian Persuratan dan Tata Usaha Pimpinan', 'kode_deputi' => 'X422', 'created_at' => NULL,],
            ['kode_biro' => 'X4221', 'nama_biro' => 'Bagian Arsip dan Perpustakaan', 'kode_deputi' => 'X422', 'created_at' => NULL,],
            ['kode_biro' => 'X4222', 'nama_biro' => 'Bagian Acara dan Protokol', 'kode_deputi' => 'X422', 'created_at' => NULL,],
            ['kode_biro' => 'X43', 'nama_biro' => 'Biro Administrasi', 'kode_deputi' => '000', 'created_at' => NULL,],
            ['kode_biro' => 'X4300', 'nama_biro' => 'Bagian Perencanaan', 'kode_deputi' => 'X430', 'created_at' => NULL,],
            ['kode_biro' => 'X4301', 'nama_biro' => 'Bagian Keuangan', 'kode_deputi' => 'X430', 'created_at' => NULL,],
            ['kode_biro' => 'X4302', 'nama_biro' => 'Bagian Evaluasi dan Pelaporan', 'kode_deputi' => 'X430', 'created_at' => NULL,],
            ['kode_biro' => 'X4310', 'nama_biro' => 'Bagian Mutasi Jabatan', 'kode_deputi' => 'X431', 'created_at' => NULL,],
            ['kode_biro' => 'X4311', 'nama_biro' => 'Bagian Kepegawaian', 'kode_deputi' => 'X431', 'created_at' => NULL,],
            [
                'kode_biro' => 'X4312',
                'nama_biro' => 'Bagian Pendidikan dan Pelatihan',
                'kode_deputi' => 'X431',
            ],
            [
                'kode_biro' => 'X4313',
                'nama_biro' => 'Bagian Tata Usaha Perbantuan',
                'kode_deputi' => 'X431',
            ],
            [
                'kode_biro' => 'X4320',
                'nama_biro' => 'Bagian Kepangkatan',
                'kode_deputi' => 'X432',
            ],
            [
                'kode_biro' => 'X4321',
                'nama_biro' => 'Bagian Pemberhentian dan Pensiun',
                'kode_deputi' => 'X432',
            ],
            [
                'kode_biro' => 'X4322',
                'nama_biro' => 'Bagian Administrasi',
                'kode_deputi' => 'X432',
            ],
            [
                'kode_biro' => 'X4330',
                'nama_biro' => 'Bagian Perlengkapan',
                'kode_deputi' => 'X433',
            ],
            [
                'kode_biro' => 'X4331',
                'nama_biro' => 'Bagian Pemeliharaan',
                'kode_deputi' => 'X433',
            ],
            [
                'kode_biro' => 'X4332',
                'nama_biro' => 'Bagian Urusan Dalam',
                'kode_deputi' => 'X433',
            ],
            [
                'kode_biro' => 'X4333',
                'nama_biro' => 'Bagian Sistem Informasi',
                'kode_deputi' => 'X433',
            ],
            [
                'kode_biro' => 'X4600',
                'nama_biro' => 'Asisten',
                'kode_deputi' => 'X460',
            ],
            [
                'kode_biro' => 'X4601',
                'nama_biro' => 'Pembantu Asisten',
                'kode_deputi' => 'X460',
            ],
            [
                'kode_biro' => 'X4602',
                'nama_biro' => 'Pengadministrasi Umum',
                'kode_deputi' => 'X460',
            ],
            [
                'kode_biro' => 'X4610',
                'nama_biro' => 'Asisten',
                'kode_deputi' => 'X461',
            ],
            [
                'kode_biro' => 'X46100',
                'nama_biro' => 'Asisten',
                'kode_deputi' => 'X4610',
            ],
            [
                'kode_biro' => 'X4611',
                'nama_biro' => 'Pembantu Asisten',
                'kode_deputi' => 'X461',
            ],
            [
                'kode_biro' => 'X4620',
                'nama_biro' => 'Asisten',
                'kode_deputi' => 'X462',
            ],
            [
                'kode_biro' => 'X4621',
                'nama_biro' => 'Pembantu Asisten',
                'kode_deputi' => 'X462',
            ],
            [
                'kode_biro' => 'X4630',
                'nama_biro' => 'Asisten',
                'kode_deputi' => 'X463',
            ],
            [
                'kode_biro' => 'X4640',
                'nama_biro' => 'Asisten',
                'kode_deputi' => 'X464',
            ],
            [
                'kode_biro' => 'X4641',
                'nama_biro' => 'Pembantu Asisten',
                'kode_deputi' => 'X464',
            ],
            [
                'kode_biro' => 'X4650',
                'nama_biro' => 'Asisten',
                'kode_deputi' => 'X465',
            ],
            [
                'kode_biro' => 'X4660',
                'nama_biro' => 'Asisten',
                'kode_deputi' => 'X466',
            ],
            [
                'kode_biro' => 'X4661',
                'nama_biro' => 'Pembantu Asisten',
                'kode_deputi' => 'X466',
            ],
            [
                'kode_biro' => 'X4670',
                'nama_biro' => 'Asisten',
                'kode_deputi' => 'X467',
            ],
            [
                'kode_biro' => 'X4671',
                'nama_biro' => 'Pembantu Asisten',
                'kode_deputi' => 'X467',
            ],
            [
                'kode_biro' => 'X4680',
                'nama_biro' => 'Asisten',
                'kode_deputi' => 'X468',
            ],
            [
                'kode_biro' => 'X4681',
                'nama_biro' => 'Pembantu Asisten',
                'kode_deputi' => 'X468',
            ],
            [
                'kode_biro' => 'X4690',
                'nama_biro' => 'Asisten',
                'kode_deputi' => 'X469',
            ],
            [
                'kode_biro' => 'X50',
                'nama_biro' => 'Biro Administrasi',
                'kode_deputi' => '000',
            ],
            [
                'kode_biro' => 'X51',
                'nama_biro' => 'Biro Administrasi',
                'kode_deputi' => '000',
            ],
            [
                'kode_biro' => 'X52',
                'nama_biro' => 'Biro Administrasi',
                'kode_deputi' => '000',
            ],
            [
                'kode_biro' => 'X53',
                'nama_biro' => 'Biro Administrasi',
                'kode_deputi' => '000',
            ],
            [
                'kode_biro' => 'X60',
                'nama_biro' => 'Biro Administrasi',
                'kode_deputi' => '000',
            ],
            [
                'kode_biro' => 'X61',
                'nama_biro' => 'Biro Administrasi',
                'kode_deputi' => '000',
            ],
            [
                'kode_biro' => 'X62',
                'nama_biro' => 'Biro Administrasi',
                'kode_deputi' => '000',
            ],
            [
                'kode_biro' => 'X63',
                'nama_biro' => 'Biro Administrasi',
                'kode_deputi' => '000',
            ],
        ];

        foreach ($datas as $key => $value) {
            Biro::create([
                'kode_biro' => $value['kode_biro'],
                'nama_biro' => $value['nama_biro'],
                'kode_deputi' => $value['kode_deputi'],
            ]);
        }
    }
}
