<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'name' => 'Sapto Harjono Wahjoe Sedjati, S.Sos., M.A.',
                'email' => 'saptoharjonowahjoesedjati@setwapresri.go.id',
                'nip' => '197010271995031001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Yayat Hidayat, S.IP.',
                'email' => 'yayathidayat@setwapresri.go.id',
                'nip' => '197404071999031001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Lely Setia Rimelanty, S.E.',
                'email' => 'lelysetiarimelanty@setwapresri.go.id',
                'nip' => ' 197111031996032001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Faniagi Hardianto, S.AP. M.AP',
                'email' => 'faniagihardianto@setwapresri.go.id',
                'nip' => '198509302005011002',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Dyah Ayu Sekarwati, S.I.Kom.',
                'email' => 'dyahayusekarwati@setwapresri.go.id',
                'nip' => '199503282019022001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Temy Pratiwi, S.H.',
                'email' => 'temypratiwi@setwapresri.go.id',
                'nip' => '199209302015032001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Ratna Wuri Handayani, S.S.T.Ars.',
                'email' => 'ratnawurihandayani@setwapresri.go.id',
                'nip' => '197703172006042002',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Iwan Heru Darmawan, S.Ikom.',
                'email' => 'iwanherudarmawan@setwapresri.go.id',
                'nip' => '198312202008011002',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Susi Susanti, S.H.',
                'email' => 'susisusanti@setwapresri.go.id',
                'nip' => '197011111997032001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Catherine Tulus Olivia, S.E., M.E.',
                'email' => 'catherinetulusolivia@setwapresri.go.id',
                'nip' => '197110192006042001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Endang Setyati, A.Md.',
                'email' => 'endangsetyati@setwapresri.go.id',
                'nip' => '196908081995032002',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Risna Afiany, S.E.',
                'email' => 'risnaafiany@setwapresri.go.id',
                'nip' => '197303172001122001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Meilani Saeciria, S.H., M.G.M.C.',
                'email' => 'meilanisaeciria@setwapresri.go.id',
                'nip' => '198005012008012015',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Irene Astika Dewi, S.I.Kom.',
                'email' => 'ireneastikadewi@setwapresri.go.id',
                'nip' => '198904032014022001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Firman Setiana, S.AP.',
                'email' => 'firmansetiana@setwapresri.go.id',
                'nip' => '197903292005011001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Supriatman, S.AP.',
                'email' => 'supriatman@setwapresri.go.id',
                'nip' => '197410281997031001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Mubowo, S.AP.',
                'email' => 'mubowo@setwapresri.go.id',
                'nip' => '197403241998031003',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Lahardian Syah, S.E., MAR.',
                'email' => 'lahardiansyah@setwapresri.go.id',
                'nip' => '198302282009011003',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Shelly Amelia, S.E.',
                'email' => 'shellyamelia@setwapresri.go.id',
                'nip' => '198906282015032001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Nabilla Arsifatika, S.I.P.',
                'email' => 'nabillaarsifatika@setwapresri.go.id',
                'nip' => '200002222025062021',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Vasya Pripagisa, S.A.P.',
                'email' => 'vasyapripagisa@setwapresri.go.id',
                'nip' => '200006142025062012',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Lestiana Kusuma Wardani, A.Md.A.P.',
                'email' => 'lestianakusumawardani@setwapresri.go.id',
                'nip' => '199607302020122017',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Jaka Sungkawa, S.Ag.',
                'email' => 'jakasungkawa@setwapresri.go.id',
                'nip' => '197506192002121001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Desi Herdiyan, S.Sos.',
                'email' => 'desiherdiyan@setwapresri.go.id',
                'nip' => '197212111997031001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Verany Zachrah',
                'email' => 'veranyzachrah@setwapresri.go.id',
                'nip' => '197209071994032001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Ambarwati',
                'email' => 'ambarwati@setwapresri.go.id',
                'nip' => '197209141995032001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Agustin Setiani',
                'email' => 'agustinsetiani@setwapresri.go.id',
                'nip' => '197808221998032001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Hasim Mukti',
                'email' => 'hasimmukti@setwapresri.go.id',
                'nip' => '197002051993031004',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Asep Saefulloh',
                'email' => 'asepsaefulloh@setwapresri.go.id',
                'nip' => '196912261998031001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Didi Sahridi',
                'email' => 'didisahridi@setwapresri.go.id',
                'nip' => '198203282005011001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Victor Anwar Riva',
                'email' => 'victoranwarriva@setwapresri.go.id',
                'nip' => '197206082005011006',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Fantry Wijayanti, S.Ak.',
                'email' => 'fantrywijayanti@setwapresri.go.id',
                'nip' => '199412152025062007',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Dede Warsa',
                'email' => 'dedewarsa@setwapresri.go.id',
                'nip' => '197504192007011001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Sri Rahayu',
                'email' => 'srirahayu@setwapresri.go.id',
                'nip' => '196905282007012001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Iwan Wahyudi',
                'email' => 'iwanwahyudi@setwapresri.go.id',
                'nip' => '197807152009011003',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Purwono Prihantoro Budi Trisnanto, S.E., M.Si.',
                'email' => 'purwonoprihantorobuditrisnanto@setwapresri.go.id',
                'nip' => '196909081990031001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Melati Putri Masniari Panjaitan, S.E.',
                'email' => 'melatiputrimasniaripanjaitan@setwapresri.go.id',
                'nip' => '199205102015032002',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Imam Sudrajat, S.E., M.Si.',
                'email' => 'imamsudrajat@setwapresri.go.id',
                'nip' => '196603181986031001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Rianita Kumalasari, S.IP, M.Com.',
                'email' => 'rianitakumalasari@setwapresri.go.id',
                'nip' => '198009302006042005',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Purnowiyanto, S.Kom.',
                'email' => 'purnowiyanto@setwapresri.go.id',
                'nip' => '197408262005011001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Rosalina Meiske Salea Battu, S.Kom., M.MSI.',
                'email' => 'rosalinameiskesaleabattu@setwapresri.go.id',
                'nip' => '198004242008012019',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Dorlan Roito Manurung, S.E.',
                'email' => 'dorlanroitomanurung@setwapresri.go.id',
                'nip' => '197609292005012001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Nur Laily Fauziah, S.E.',
                'email' => 'nurlailyfauziah@setwapresri.go.id',
                'nip' => '198505232008012001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Primurnita Wiryanti, S.E., M.Si.',
                'email' => 'primurnitawiryanti@setwapresri.go.id',
                'nip' => '198410192009122001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Diar Indriatno, S.Sos., M.AP.',
                'email' => 'diarindriatno@setwapresri.go.id',
                'nip' => '196905271997031001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Sari Dwi Handiny, S.Kom., M.PubAdmin (Pol)',
                'email' => 'saridwihandiny@setwapresri.go.id',
                'nip' => '198604012009012001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Samsam Sambas Wahyudi, S.IP.',
                'email' => 'samsamsambaswahyudi@setwapresri.go.id',
                'nip' => '198102112009011006',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Sari Tusiarlina, S.H.',
                'email' => 'saritusiarlina@setwapresri.go.id',
                'nip' => '198208262005012001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Triana Rochmatun Handayani, S.Si.',
                'email' => 'trianarochmatunhandayani@setwapresri.go.id',
                'nip' => '198009202008012013',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Hadi Meidiyan, S.E.',
                'email' => 'hadimeidiyan@setwapresri.go.id',
                'nip' => '198405272008011004',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Diah Pratiwi, S.E.',
                'email' => 'diahpratiwi@setwapresri.go.id',
                'nip' => '198508132008012001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'R. Muhammad Rizqi Attamimi, S.Kom., M.M.S.I.',
                'email' => 'r.muhammadrizqiattamimi@setwapresri.go.id',
                'nip' => '198807212010121001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Asep Patrika, S.E., M.Ak.',
                'email' => 'aseppatrika@setwapresri.go.id',
                'nip' => '198611062009121003',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Atiek Susilowati, S.E.',
                'email' => 'atieksusilowati@setwapresri.go.id',
                'nip' => '197512032014062001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Andri Novrano Sitorus, S.E.',
                'email' => 'andrinovranositorus@setwapresri.go.id',
                'nip' => '198611172018011001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Devi Widyana Wulan, S.A.B.',
                'email' => 'deviwidyanawulan@setwapresri.go.id',
                'nip' => '199607042025062009',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Rezkyan Kresna Dwipayana, S.AB.',
                'email' => 'rezkyankresnadwipayana@setwapresri.go.id',
                'nip' => '200204302025061007',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Haryatmoko, A.Md.',
                'email' => 'haryatmoko@setwapresri.go.id',
                'nip' => '197705272006041002',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Toto Budi Kurniawan, A.Md.',
                'email' => 'totobudikurniawan@setwapresri.go.id',
                'nip' => '197402052005011002',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Ahmad Marulloh, A.Md.Ak.',
                'email' => 'ahmadmarulloh@setwapresri.go.id',
                'nip' => '199711272025061009',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Juliana Zakiah, A.Md.A.B.',
                'email' => 'julianazakiah@setwapresri.go.id',
                'nip' => '199907152025062013',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Al Alaq Fahamzah',
                'email' => 'alalaqfahamzah@setwapresri.go.id',
                'nip' => '198407072005012001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Fahri',
                'email' => 'fahri@setwapresri.go.id',
                'nip' => '197210022005011001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Supriyatno Widodo',
                'email' => 'supriyatnowidodo@setwapresri.go.id',
                'nip' => '197405142005011001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Rika Anggasari',
                'email' => 'rikaanggasari@setwapresri.go.id',
                'nip' => '198110162005012002',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Rika Kusmawati',
                'email' => 'rikakusmawati@setwapresri.go.id',
                'nip' => '198108222005012001',
                'unit_kerja' => 'Biro Perencanaan dan Keuangan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Yan Adikusuma, S.Kom., M.Eng.',
                'email' => 'yanadikusuma@setwapresri.go.id',
                'nip' => '197506251994121001',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
                'role' => 'super_admin'
            ],
            [
                'name' => 'Dr. Dedy Triharjanto, S.E., M.M.',
                'email' => 'dr.dedytriharjanto@setwapresri.go.id',
                'nip' => '197203271998031001',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Fajar Triwardono, S.T., M.T.',
                'email' => 'fajartriwardono@setwapresri.go.id',
                'nip' => '199002112015031001',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
                'role' => 'admin_ruangan'
            ],
            [
                'name' => 'Muhammad Alkautsar, S.H., M.H.',
                'email' => 'muhammadalkautsar@setwapresri.go.id',
                'nip' => '198006302005011006',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Hari Sugiharto, S.T., M.M.',
                'email' => 'harisugiharto@setwapresri.go.id',
                'nip' => '197612051996031002',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
                'role' => 'admin_atk'
            ],
            [
                'name' => 'Fatia Hizriani, S.Pd., M.M.',
                'email' => 'fatiahizriani@setwapresri.go.id',
                'nip' => '197805202005012026',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Sutedjo, S.E.',
                'email' => 'sutedjo@setwapresri.go.id',
                'nip' => '197106261998031001',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Angga Dwijayanti, S.Kom.',
                'email' => 'anggadwijayanti@setwapresri.go.id',
                'nip' => '198706212015032002',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Danang Ari Suwito, S.Sos.',
                'email' => 'danangarisuwito@setwapresri.go.id',
                'nip' => '198707042015031001',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Ika Mailani, S.T., M.T.I.',
                'email' => 'ikamailani@setwapresri.go.id',
                'nip' => '198505092009012005',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Halim Fadillah Suwito Jati, S.E.',
                'email' => 'halimfadillahsuwitojati@setwapresri.go.id',
                'nip' => '199110162015031001',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
                'role' => 'admin_kerusakan_gedung'
            ],
            [
                'name' => 'Ismaja Rumalutur, S.E.',
                'email' => 'ismajarumalutur@setwapresri.go.id',
                'nip' => '196807151990031001',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Farid Ridwansyah, S.AP.',
                'email' => 'faridridwansyah@setwapresri.go.id',
                'nip' => '198202032005011004',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Pamuji',
                'email' => 'pamuji@setwapresri.go.id',
                'nip' => '196804271995031001',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Budhi Afriyanto, S.AP.',
                'email' => 'budhiafriyanto@setwapresri.go.id',
                'nip' => '197904042007011002',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Imam Kusaeri',
                'email' => 'imamkusaeri@setwapresri.go.id',
                'nip' => '197203022005011010',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Repi Sopiana',
                'email' => 'repisopiana@setwapresri.go.id',
                'nip' => '197205012005011001',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Sutiyono',
                'email' => 'sutiyono@setwapresri.go.id',
                'nip' => '197206172005011007',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Widodo',
                'email' => 'widodo@setwapresri.go.id',
                'nip' => '197205082005011001',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Isnandy Arief Widodo, S.T.',
                'email' => 'isnandyariefwidodo@setwapresri.go.id',
                'nip' => '198910212015031001',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Azis Rahman',
                'email' => 'azisrahman@setwapresri.go.id',
                'nip' => '197312092007011002',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Taufiq Ilham Maghfury, S.T.',
                'email' => 'taufiqilhammaghfury@setwapresri.go.id',
                'nip' => '199611102025061011',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serma Abdul Sakran S. Pagan',
                'email' => 'sermaabdulsakrans.pagan@setwapresri.go.id',
                'nip' => '21040027590683',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Pelda Muhaji',
                'email' => 'peldamuhaji@setwapresri.go.id',
                'nip' => '3920722450173',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serma Samsul Huda',
                'email' => 'sermasamsulhuda@setwapresri.go.id',
                'nip' => '31940570830974',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Bripka Ika Mardika Putri, A. Md.',
                'email' => 'bripkaikamardikaputri@setwapresri.go.id',
                'nip' => '86082000',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serma Indra Kirana',
                'email' => 'sermaindrakirana@setwapresri.go.id',
                'nip' => '518595',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Dadang Sasmita',
                'email' => 'dadangsasmita@setwapresri.go.id',
                'nip' => '197004022007011004',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Nami Bahtiar',
                'email' => 'namibahtiar@setwapresri.go.id',
                'nip' => '197107052006041009',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Supriyanta',
                'email' => 'supriyanta@setwapresri.go.id',
                'nip' => '197303262007011003',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Udin Saefudin',
                'email' => 'udinsaefudin@setwapresri.go.id',
                'nip' => '197104072006041006',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serma Abdul Munir',
                'email' => 'sermaabdulmunir@setwapresri.go.id',
                'nip' => '31940365900873',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serma Retno Susilo',
                'email' => 'sermaretnosusilo@setwapresri.go.id',
                'nip' => '21040039060985',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serma Hayatudin',
                'email' => 'sermahayatudin@setwapresri.go.id',
                'nip' => '21050097950682',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Slamet Priyanto',
                'email' => 'slametpriyanto@setwapresri.go.id',
                'nip' => '196910082009011001',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serma Cecep Subarnas',
                'email' => 'sermacecepsubarnas@setwapresri.go.id',
                'nip' => '31940478520773',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serma Tku Eko Sigit Prabowo',
                'email' => 'sermatkuekosigitprabowo@setwapresri.go.id',
                'nip' => '110190',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Wardi',
                'email' => 'wardi@setwapresri.go.id',
                'nip' => '197402262007011002',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Nia Nadiawati, A.Md.',
                'email' => 'nianadiawati@setwapresri.go.id',
                'nip' => '199711172025062012',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Bima Hutari, A.Md.T.',
                'email' => 'bimahutari@setwapresri.go.id',
                'nip' => '200208182025062009',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Bony Pakpahan, A.Md.',
                'email' => 'bonypakpahan@setwapresri.go.id',
                'nip' => '199508132025061004',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Pretty Marpaung, A.Md.T.',
                'email' => 'prettymarpaung@setwapresri.go.id',
                'nip' => '200203092025062007',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Yolanda Henita Paraswari, A.Md.T.',
                'email' => 'yolandahenitaparaswari@setwapresri.go.id',
                'nip' => '200001272025062011',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serka Abdul Jabbar Muhaimin',
                'email' => 'serkaabduljabbarmuhaimin@setwapresri.go.id',
                'nip' => '538157',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serka Isnan Fairuz Nizar',
                'email' => 'serkaisnanfairuznizar@setwapresri.go.id',
                'nip' => '21120081020192',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serka Purnomo Jati Waluyo, S.I.P.',
                'email' => 'serkapurnomojatiwaluyo@setwapresri.go.id',
                'nip' => '31000393730181',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serka Esa Lukman Bayu Andrianto',
                'email' => 'serkaesalukmanbayuandrianto@setwapresri.go.id',
                'nip' => '118405',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Sertu Dwi lrvanto',
                'email' => 'sertudwilrvanto@setwapresri.go.id',
                'nip' => '529045',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Sertu Gumilang Ksatriaji Nugroho',
                'email' => 'sertugumilangksatriajinugroho@setwapresri.go.id',
                'nip' => '41719702545967',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serda Abdul Wahid Aziz',
                'email' => 'serdaabdulwahidaziz@setwapresri.go.id',
                'nip' => '131224',
                'unit_kerja' => 'Biro Umum',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Erick Griwantara, S.IP., M.Pub.Pol.',
                'email' => 'erickgriwantara@setwapresri.go.id',
                'nip' => '197802202002121001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Maisaroh Nurharjanti, S.Ag., MA.',
                'email' => 'maisarohnurharjanti@setwapresri.go.id',
                'nip' => '197501272005012003',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Woro Dyah Tri Siswanti, S.T., M.E.',
                'email' => 'worodyahtrisiswanti@setwapresri.go.id',
                'nip' => '197911142005012002',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Wisnu Aribowo, S.Sos.',
                'email' => 'wisnuaribowo@setwapresri.go.id',
                'nip' => '198408072008011006',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Ade Ulfah Rahayu Ningsih, S.E.',
                'email' => 'adeulfahrahayuningsih@setwapresri.go.id',
                'nip' => '197901032005012001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Prima Analisa, S.Sos., M.A.',
                'email' => 'primaanalisa@setwapresri.go.id',
                'nip' => '198401232008012004',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Suryati Pangestu Prihandini, S.Sos.',
                'email' => 'suryatipangestuprihandini@setwapresri.go.id',
                'nip' => '197804082005012001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Leony Stephanie Dima Gah, S.Kom., M.I.S.',
                'email' => 'leonystephaniedimagah@setwapresri.go.id',
                'nip' => '198607292009012001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Mohammad Reza Wardy, S.S. MIR.',
                'email' => 'mohammadrezawardy@setwapresri.go.id',
                'nip' => '198312012010121003',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Sumiati, S.IP.',
                'email' => 'sumiati@setwapresri.go.id',
                'nip' => '197204011996032001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Mukti Cahyani, S.H., M.H.',
                'email' => 'mukticahyani@setwapresri.go.id',
                'nip' => '198502122012122001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Arif Alfan Haji, S.IAN.',
                'email' => 'arifalfanhaji@setwapresri.go.id',
                'nip' => '198711252015031001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Jafar Fikri Alkadrie, S.H.Int',
                'email' => 'jafarfikrialkadrie@setwapresri.go.id',
                'nip' => '199404062019021001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Mulyani',
                'email' => 'mulyani@setwapresri.go.id',
                'nip' => '197006021995032001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Kwinta Masalit, S.AP.',
                'email' => 'kwintamasalit@setwapresri.go.id',
                'nip' => '197109082005011008',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'M. Andy Burhan, S.Sos.',
                'email' => 'm.andyburhan@setwapresri.go.id',
                'nip' => '198209242005011001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Erni Padilah, S. AB.',
                'email' => 'ernipadilah@setwapresri.go.id',
                'nip' => '199106252015032001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Nadira Fitria, S.Hum., M.S.M.',
                'email' => 'nadirafitria@setwapresri.go.id',
                'nip' => '199506052020122018',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Muis Syaiful Anuar',
                'email' => 'muissyaifulanuar@setwapresri.go.id',
                'nip' => '197607132005011001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Wenny Setia Ningsih',
                'email' => 'wennysetianingsih@setwapresri.go.id',
                'nip' => '198007052005012001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Yue Awatef, S.A.B.',
                'email' => 'yueawatef@setwapresri.go.id',
                'nip' => '199811262025062008',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Indah Dwi Kristanti, S.Akun.',
                'email' => 'indahdwikristanti@setwapresri.go.id',
                'nip' => '199906092025062015',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Sekar Laksmicita Cakramurti, S.I.P.',
                'email' => 'sekarlaksmicitacakramurti@setwapresri.go.id',
                'nip' => '200001182025062008',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Tazkia Amara, S.S.',
                'email' => 'tazkiaamara@setwapresri.go.id',
                'nip' => '200002242025062016',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Darsono',
                'email' => 'darsono@setwapresri.go.id',
                'nip' => '197004152006041006',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Koko Hendrik Handriyuso',
                'email' => 'kokohendrikhandriyuso@setwapresri.go.id',
                'nip' => '197308152007011003',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Suheli',
                'email' => 'suheli@setwapresri.go.id',
                'nip' => '197004212006041001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Sunarman',
                'email' => 'sunarman@setwapresri.go.id',
                'nip' => '197706122007101007',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Titien Pradani, S.I.Kom.',
                'email' => 'titienpradani@setwapresri.go.id',
                'nip' => '199304052018012003',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Diman',
                'email' => 'diman@setwapresri.go.id',
                'nip' => '197806172009011004',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serma Setiyadi Jati Atmaja, S.H.',
                'email' => 'sermasetiyadijatiatmaja@setwapresri.go.id',
                'nip' => '21050102560486',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Arya Bagus Sanjaya, A.Md',
                'email' => 'aryabagussanjaya@setwapresri.go.id',
                'nip' => '198807152018011001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Ghea Resta Meida, A.Md.Li.',
                'email' => 'ghearestameida@setwapresri.go.id',
                'nip' => '199705162019022001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Nabilah, A.Md.Kom.',
                'email' => 'nabilah@setwapresri.go.id',
                'nip' => '199106142018012001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serma Ttu/W Pipit Sere',
                'email' => 'sermattu/wpipitsere@setwapresri.go.id',
                'nip' => '108308',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Reda Waritsunal Firdaus Sukandar, A.Md.',
                'email' => 'redawaritsunalfirdaussukandar@setwapresri.go.id',
                'nip' => '199408082019021001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Siske Adesma, A.Md.',
                'email' => 'siskeadesma@setwapresri.go.id',
                'nip' => '199512262018012001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Yuyun Kusumawardani, A.Md.A.P.S.',
                'email' => 'yuyunkusumawardani@setwapresri.go.id',
                'nip' => '199606032018012001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serma Kristiningrum Wulandari',
                'email' => 'sermakristiningrumwulandari@setwapresri.go.id',
                'nip' => '536831',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serma (K) Ayu Setyorini',
                'email' => 'ayusetyorini@setwapresri.go.id',
                'nip' => '21090271240990',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Dita Yuniasari, A.Md.Par.',
                'email' => 'ditayuniasari@setwapresri.go.id',
                'nip' => '199806132025062005',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Indah Rahma Yulia, A.Md.Kom.',
                'email' => 'indahrahmayulia@setwapresri.go.id',
                'nip' => '199707012025062010',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Nurul Izzah Yahya, A.Md.',
                'email' => 'nurulizzahyahya@setwapresri.go.id',
                'nip' => '200105302025062015',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serka Pdk/W Ayu Qhurniawati',
                'email' => 'serkapdk/wayuqhurniawati@setwapresri.go.id',
                'nip' => '115225',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Edi Sujanto',
                'email' => 'edisujanto@setwapresri.go.id',
                'nip' => '197003181998031001',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Asrori',
                'email' => 'asrori@setwapresri.go.id',
                'nip' => '197211192006041011',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serka (K) Ani Kurniawati',
                'email' => 'serka(k)anikurniawati@setwapresri.go.id',
                'nip' => '21130217090494',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serka Dwi Puspitasari',
                'email' => 'serkadwipuspitasari@setwapresri.go.id',
                'nip' => '542613',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Serka Wahyu Nur Utami',
                'email' => 'serkawahyunurutami@setwapresri.go.id',
                'nip' => '542630',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Sertu (K) Devi Hotma Merysion Br. Pangaribuan',
                'email' => 'devihotmamerysionbr.pangaribuan@setwapresri.go.id',
                'nip' => '21150240321293',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Sertu (K) Wiwid Sivi Wulandari S.',
                'email' => 'wiwidsiviwulandaris.@setwapresri.go.id',
                'nip' => '21150230590695',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Briptu Sandrea Maretasha Adinata, S.Sos.',
                'email' => 'briptusandreamaretashaadinata@setwapresri.go.id',
                'nip' => '97030748',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Briptu Delvyan Putri Suryaningrum, S.H.',
                'email' => 'briptudelvyanputrisuryaningrum@setwapresri.go.id',
                'nip' => '98010487',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Briptu Putu Bintang Seviana Dewi, S.H.',
                'email' => 'briptuputubintangsevianadewi@setwapresri.go.id',
                'nip' => '01050182',
                'unit_kerja' => 'Biro Protokol dan Kerumahtanggaan',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Drs. Rusmin Nuryadin, M.H.',
                'email' => 'drs.rusminnuryadin@setwapresri.go.id',
                'nip' => '196606021992031004',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Edi Purwanto, S.A.P., M.P.M',
                'email' => 'edipurwanto@setwapresri.go.id',
                'nip' => '198412282009121001',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Muhammad David Masri, S.Sos., M.H.',
                'email' => 'muhammaddavidmasri@setwapresri.go.id',
                'nip' => '197412291998031005',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Robby Junia Prihana, S.Sos., M.M.',
                'email' => 'robbyjuniaprihana@setwapresri.go.id',
                'nip' => '197806102008011014',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Andri Suharyadi Kurniawan, S.E., M.T.',
                'email' => 'andrisuharyadikurniawan@setwapresri.go.id',
                'nip' => '197503262006041001',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Siti Khodijah, S.Pd., M.GMC.',
                'email' => 'sitikhodijah@setwapresri.go.id',
                'nip' => '198005052005012001',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Edy Kasrody, S.Sos.',
                'email' => 'edykasrody@setwapresri.go.id',
                'nip' => '196807041989031002',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Luci Fannya, S.E.',
                'email' => 'lucifannya@setwapresri.go.id',
                'nip' => '196902051995032002',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Ristinah, S.S.',
                'email' => 'ristinah@setwapresri.go.id',
                'nip' => '198102252008012013',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Nanda Nugrahanti, S.Ikom., M.Commun.',
                'email' => 'nandanugrahanti@setwapresri.go.id',
                'nip' => '198409182008012004',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Dwiana Marcheni Arumningtyas, S.S.',
                'email' => 'dwianamarcheniarumningtyas@setwapresri.go.id',
                'nip' => '199203022014022002',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Sheila Merista, S.S.',
                'email' => 'sheilamerista@setwapresri.go.id',
                'nip' => '199006262014022002',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Sherin Novira Dewi Afianty, S.IP., M. Arts.',
                'email' => 'sherinnoviradewiafianty@setwapresri.go.id',
                'nip' => '198411242010122002',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Muhammad Abduh Abdullah, S.H.',
                'email' => 'muhammadabduhabdullah@setwapresri.go.id',
                'nip' => '197407271995111001',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Deni Setiadhi, S.Kom.',
                'email' => 'denisetiadhi@setwapresri.go.id',
                'nip' => '198412272009021001',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Novia Anggi Ratnasari, S.I.Kom.',
                'email' => 'noviaanggiratnasari@setwapresri.go.id',
                'nip' => '199011252015032001',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Mayrizky Ramadhani, S.I.Kom.',
                'email' => 'mayrizkyramadhani@setwapresri.go.id',
                'nip' => '198705052018012001',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Muhamad Zulfikar Aristianto, S.I.Kom.',
                'email' => 'muhamadzulfikararistianto@setwapresri.go.id',
                'nip' => '199007092018011001',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Almanda Triandini Yogiswari, S.Pd.',
                'email' => 'almandatriandiniyogiswari@setwapresri.go.id',
                'nip' => '200008032025062015',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Grysella, S.Pd.',
                'email' => 'grysella@setwapresri.go.id',
                'nip' => '199712052025062006',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Arief Hendratno, A.Md.',
                'email' => 'ariefhendratno@setwapresri.go.id',
                'nip' => '197101071997031004',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Asprilla Wahyu Dona Dony, A.Md.I.K',
                'email' => 'asprillawahyudonadony@setwapresri.go.id',
                'nip' => '199304022019021001',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Mita Defitri, A.Md.',
                'email' => 'mitadefitri@setwapresri.go.id',
                'nip' => '199812182025062009',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Ramadhan Khodarul Hakim, A.Md.',
                'email' => 'ramadhankhodarulhakim@setwapresri.go.id',
                'nip' => '200112062025061003',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Yusnaini, S.Sos.',
                'email' => 'yusnaini@setwapresri.go.id',
                'nip' => '197801182002122001',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Mahdiyono, S.Kom.',
                'email' => 'mahdiyono@setwapresri.go.id',
                'nip' => '197911172005011006',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Yohannes Liniandus',
                'email' => 'yohannesliniandus@setwapresri.go.id',
                'nip' => '197502091997031001',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Sri Endang Agustiningsih',
                'email' => 'sriendangagustiningsih@setwapresri.go.id',
                'nip' => '197408082007012002',
                'unit_kerja' => 'Biro Pers, Media, dan Informasi',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Developer Setwapres',
                'email' => 'developer@setwapresri.go.id',
                'nip' => '085343652494',
                'role' => 'super_admin',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
        ];

        $dataX = [
            [
                'name' => 'Sapto Harjono Wahjoe Sedjati, S.Sos., M.A.',
                'email' => 'saptoharjonowahjoesedjati@setwapresri.go.id',
                'nip' => '197010271995031001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Yayat Hidayat, S.IP.',
                'email' => 'yayathidayat@setwapresri.go.id',
                'nip' => '197404071999031001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Lely Setia Rimelanty, S.E.',
                'email' => 'lelysetiarimelanty@setwapresri.go.id',
                'nip' => ' 197111031996032001',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
            [
                'name' => 'Developer Setwapres',
                'email' => 'developer@setwapresri.go.id',
                'nip' => '085343652494',
                'role' => 'super_admin',
                'unit_kerja' => 'Biro Tata Usaha dan Sumber Daya Manusia',
                'instansi_id' => 4,
            ],
        ];

        foreach ($dataX as $key => $value) {
            $user =  User::create([
                'name' => $value['name'],
                'instansi_id' => $value['instansi_id'],
                'email' => $value['email'],
                'nip' => $value['nip'],
                'unit_kerja' => $value['unit_kerja'],
                'password' => Hash::make($value['nip']),
            ]);

            $user->assignRole($value['role'] ?? 'pegawai');
        }
    }
}
