<?php

namespace Database\Seeders;

use App\Models\DaftarAtk;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DaftarAtkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $atks = [
            ['name' => 'Bollpoint Bolliner Pilot', 'satuan' => 'Buah', 'kategori_atk_id' => '1'],
            ['name' => 'Bollpoint Hi-Tech Point V.5', 'satuan' => 'Buah', 'kategori_atk_id' => '1'],
            ['name' => 'Bollpoint Uniball Signo', 'satuan' => 'Buah', 'kategori_atk_id' => '1'],
            ['name' => 'Pensil Staedtler 2B', 'satuan' => 'Buah', 'kategori_atk_id' => '1'],
            ['name' => 'Spidol Gold/Silver besar', 'satuan' => 'Buah', 'kategori_atk_id' => '1'],
            ['name' => 'Spidol Permanent Art Line 107R (Merah)', 'satuan' => 'Buah', 'kategori_atk_id' => '1'],
            ['name' => 'Spidol Whiteboard/ Artline 157R merah (Di sakti Spidol Artline 500)', 'satuan' => 'Buah', 'kategori_atk_id' => '1'],
            ['name' => 'Spidol Snowman Kecil', 'satuan' => 'Buah', 'kategori_atk_id' => '1'],
            ['name' => 'Bollpoint Boldliner 1.0 Hitam/Biru', 'satuan' => 'Buah', 'kategori_atk_id' => '1'],
            ['name' => 'Pulpen Zebra Sarasa Gel Ink Roller Ball clip 0,7 hitam dan biru', 'satuan' => 'Buah', 'kategori_atk_id' => '1'],
            ['name' => 'Bollpoin Kenko Retractable gel pen K1', 'satuan' => 'Buah', 'kategori_atk_id' => '1'],
            ['name' => 'Spidol Snowman Whiteboard ABG-12 hitam/biru', 'satuan' => 'Buah', 'kategori_atk_id' => '1'],
            ['name' => 'Bollpoint Uniball Signo Broad', 'satuan' => 'Buah', 'kategori_atk_id' => '1'],
            ['name' => 'Spidol Snowman AG-12 Permanent', 'satuan' => 'Buah', 'kategori_atk_id' => '1'],
            ['name' => 'Stabillo Swing Cool', 'satuan' => 'Buah', 'kategori_atk_id' => '1'],
            ['name' => 'Tinta Stempel', 'satuan' => 'Tube', 'kategori_atk_id' => '2'],
            ['name' => 'Tinta Stempel Trodat 7011', 'satuan' => 'Tube', 'kategori_atk_id' => '2'],
            ['name' => 'Binder Clips No.105', 'satuan' => 'Dus kecil', 'kategori_atk_id' => '3'],
            ['name' => 'Binder Clips No.107', 'satuan' => 'Dus kecil', 'kategori_atk_id' => '3'],
            ['name' => 'Binder Clips No.111', 'satuan' => 'Dus kecil', 'kategori_atk_id' => '3'],
            ['name' => 'Binder Clips No.155', 'satuan' => 'Dus kecil', 'kategori_atk_id' => '3'],
            ['name' => 'Binder Clips No. 200', 'satuan' => 'Dus kecil', 'kategori_atk_id' => '3'],
            ['name' => 'Binder Clips No.260', 'satuan' => 'Dus kecil', 'kategori_atk_id' => '3'],
            ['name' => 'Clips Paper No.3', 'satuan' => 'Dus kecil', 'kategori_atk_id' => '3'],
            ['name' => 'Penghapus Whiteboard', 'satuan' => 'Buah', 'kategori_atk_id' => '4'],
            ['name' => 'Penghapus Pita IBM/Carera', 'satuan' => 'Rol', 'kategori_atk_id' => '4'],
            ['name' => 'Remover', 'satuan' => 'Buah', 'kategori_atk_id' => '4'],
            ['name' => 'Tip Ex Pen/Correction Pen ZL62-W Pentel', 'satuan' => 'Buah', 'kategori_atk_id' => '4'],
            ['name' => 'Tip ex Joyco CT-522', 'satuan' => 'Buah', 'kategori_atk_id' => '4'],
            ['name' => 'Penghapus Faber Castel 20-L', 'satuan' => 'Buah', 'kategori_atk_id' => '4'],
            ['name' => 'Bloknote/Memo Dinas Ukuran A5', 'satuan' => 'Buah', 'kategori_atk_id' => '5'],
            ['name' => 'Bloknote/Memo Dinas Kecil Warna Orange', 'satuan' => 'Buah', 'kategori_atk_id' => '5'],
            ['name' => 'Buku Agenda Surat Masuk Uk F4 Merah Isi 300 Lbr', 'satuan' => 'Buah', 'kategori_atk_id' => '5'],
            ['name' => 'Buku Expedisi Merah Isi 300 Lbr', 'satuan' => 'Buah', 'kategori_atk_id' => '5'],
            ['name' => 'Buku Agenda Quarto Isi 100 Lembar', 'satuan' => 'Buah', 'kategori_atk_id' => '5'],
            ['name' => 'Buku Agenda Folio Isi 100 Lembar', 'satuan' => 'Buah', 'kategori_atk_id' => '5'],
            ['name' => 'Buku Expedisi Isi 100 Lembar', 'satuan' => 'Buah', 'kategori_atk_id' => '5'],
            ['name' => 'Bloknote Paperline ukuran A4', 'satuan' => 'Buah', 'kategori_atk_id' => '5'],
            ['name' => 'Bloknote A5 Merk Paperline', 'satuan' => 'Buah', 'kategori_atk_id' => '5'],
            ['name' => 'Bloknote/Memo kecil cover putih Logo Kemensetneg RI, Setwapres', 'satuan' => 'Buah', 'kategori_atk_id' => '5'],
            ['name' => 'Bloknote/Memo kecil cover hitam Logo Wakil Presiden RI', 'satuan' => 'Buah', 'kategori_atk_id' => '5'],
            ['name' => 'Buku Nota besar R2', 'satuan' => 'Buah', 'kategori_atk_id' => '5'],
            ['name' => 'Box File Jumbo Bindex', 'satuan' => 'Buah', 'kategori_atk_id' => '6'],
            ['name' => 'Map Daichi Clear Sleves 9001 uk. A4', 'satuan' => 'Buah', 'kategori_atk_id' => '6'],
            ['name' => 'Map Bussiness File Plastik Ukuran A4', 'satuan' => 'Buah', 'kategori_atk_id' => '6'],
            ['name' => 'Map Bussiness File Plastik Ukuran F4 Gunshu 390F', 'satuan' => 'Buah', 'kategori_atk_id' => '6'],
            ['name' => 'Ordner Merk Bambi 1010 (Di Sakti 2121)', 'satuan' => 'Buah', 'kategori_atk_id' => '6'],
            ['name' => 'Ordner Folio 717 Bindex', 'satuan' => 'Buah', 'kategori_atk_id' => '6'],
            ['name' => 'Standar Buku Merk Lion', 'satuan' => 'Set', 'kategori_atk_id' => '6'],
            ['name' => 'Stop Map Polos Diamond 5002 (isi 50 buah)', 'satuan' => 'Dus', 'kategori_atk_id' => '6'],
            ['name' => 'Stop Map Putih Logo Bintang Kemsetneg Setwapres, Art Carton Putih', 'satuan' => 'Buah', 'kategori_atk_id' => '6'],
            ['name' => 'Map Bp. Wapres bahan Art Carton Ukuran A5', 'satuan' => 'Buah', 'kategori_atk_id' => '6'],
            ['name' => 'Map Plastik Daichi file 9002 uk. F4', 'satuan' => 'Buah', 'kategori_atk_id' => '6'],
            ['name' => 'Plastik Bantex Uk. F4 (isi 100 lembar)', 'satuan' => 'Pac', 'kategori_atk_id' => '6'],
            ['name' => 'Plastik Bantex uk: A4 isi 100/pac', 'satuan' => 'Pac', 'kategori_atk_id' => '6'],
            ['name' => 'Map gantung Fujita ukuran F4 isi 50 buah', 'satuan' => 'Pac/Dus', 'kategori_atk_id' => '6'],
            ['name' => 'Clear Holder Ukuran F4 CH.40', 'satuan' => 'Buah', 'kategori_atk_id' => '6'],
            ['name' => 'Map Bp. Wakil Presiden RI warna hitam', 'satuan' => 'Buah', 'kategori_atk_id' => '6'],
            ['name' => 'Map lipat Acordion warna cream lis linen merah', 'satuan' => 'Buah', 'kategori_atk_id' => '6'],
            ['name' => 'Map Folder Arsip Bahan kartu tik', 'satuan' => 'Buah', 'kategori_atk_id' => '6'],
            ['name' => 'Bantex Box File 4011', 'satuan' => 'Buah', 'kategori_atk_id' => '6'],
            ['name' => 'Penggaris Plastik 30 Cm', 'satuan' => 'Buah', 'kategori_atk_id' => '7'],
            ['name' => 'Penggaris Besi 30 Cm', 'satuan' => 'Buah', 'kategori_atk_id' => '7'],
            ['name' => 'Penggaris Plastik 50 Cm', 'satuan' => 'Buah', 'kategori_atk_id' => '7'],
            ['name' => 'Cutter Besar L -500', 'satuan' => 'Buah', 'kategori_atk_id' => '8'],
            ['name' => 'Cutter Kecil A- 300', 'satuan' => 'Buah', 'kategori_atk_id' => '8'],
            ['name' => 'Pita Olympia Carera (AX200)', 'satuan' => 'Rol', 'kategori_atk_id' => '9'],
            ['name' => 'Celotape uk. 1" Daimaru', 'satuan' => 'Rol', 'kategori_atk_id' => '10'],
            ['name' => 'Double Tape Uk. 1"', 'satuan' => 'Rol', 'kategori_atk_id' => '10'],
            ['name' => 'Lem cair Joyco', 'satuan' => 'Tube', 'kategori_atk_id' => '10'],
            ['name' => 'Lem Pasta', 'satuan' => 'Tube', 'kategori_atk_id' => '10'],
            ['name' => 'Lem Spraymount Artist Besar 290 Gram', 'satuan' => 'Kaleng', 'kategori_atk_id' => '10'],
            ['name' => 'Lem Pritt besar 40 gram/Lem Stick', 'satuan' => 'Buah', 'kategori_atk_id' => '10'],
            ['name' => 'Lakban Coklat Plastik', 'satuan' => '', 'kategori_atk_id' => '10'],
            ['name' => 'Lem Fox 1 kg', 'satuan' => 'Tube', 'kategori_atk_id' => '10'],
            ['name' => 'Lakban bening Daimaru ukuran 2 inc', 'satuan' => 'Buah', 'kategori_atk_id' => '10'],
            ['name' => 'Lakban hitam', 'satuan' => 'Roll', 'kategori_atk_id' => '10'],
            ['name' => 'UHU Lem kertas Stick 40 gram ', 'satuan' => 'Buah', 'kategori_atk_id' => '10'],
            ['name' => 'Bak Stempel', 'satuan' => 'Buah', 'kategori_atk_id' => '11'],
            ['name' => 'Isi Max Stapler No.3. 1M', 'satuan' => 'Dus', 'kategori_atk_id' => '11'],
            ['name' => 'Isi Cutter Kecil A-100', 'satuan' => 'Tube', 'kategori_atk_id' => '11'],
            ['name' => 'Max Stapler HD.50', 'satuan' => 'Buah', 'kategori_atk_id' => '11'],
            ['name' => 'Magnit White Board', 'satuan' => 'Buah', 'kategori_atk_id' => '11'],
            ['name' => 'Pembolong Kertas Besar No.85', 'satuan' => 'Buah', 'kategori_atk_id' => '11'],
            ['name' => 'Rautan Pensil Carl Angel V', 'satuan' => 'Buah', 'kategori_atk_id' => '11'],
            ['name' => 'Tempat Pensil (Caddy Set) Kenko 8312', 'satuan' => 'Buah', 'kategori_atk_id' => '11'],
            ['name' => 'Pembolong Kertas Kecil', 'satuan' => 'Buah', 'kategori_atk_id' => '11'],
            ['name' => 'Rautan Pencil Carl Angel Kecil', 'satuan' => 'Buah', 'kategori_atk_id' => '11'],
            ['name' => 'Isi Cutter L150 Tampungan', 'satuan' => 'Tube', 'kategori_atk_id' => '11'],
            ['name' => 'Isi Cutter L150 Setara Kenko', 'satuan' => 'Tube', 'kategori_atk_id' => '11'],
            ['name' => 'Post it Sign here ', 'satuan' => 'Pad', 'kategori_atk_id' => '11'],
            ['name' => 'Post-it No.654 (tampungan)', 'satuan' => 'Pad', 'kategori_atk_id' => '11'],
            ['name' => 'Post-it No.655, 3M (tampungan)', 'satuan' => 'Pad', 'kategori_atk_id' => '11'],
            ['name' => 'Post-it Pronto', 'satuan' => 'Pad', 'kategori_atk_id' => '11'],
            ['name' => 'Gunting Sedang Joyko SC-838', 'satuan' => 'Buah', 'kategori_atk_id' => '11'],
            ['name' => 'Gunting Besar Joyko SC-848', 'satuan' => 'Buah', 'kategori_atk_id' => '11'],
            ['name' => 'Dispenser Isolasi 1" Lion 50', 'satuan' => 'Buah', 'kategori_atk_id' => '11'],
            ['name' => 'Kertas Foto Copy A3 80 Gram', 'satuan' => 'Rim', 'kategori_atk_id' => '12'],
            ['name' => 'Kertas Foto Copy F4 80 Gram', 'satuan' => 'Rim', 'kategori_atk_id' => '12'],
            ['name' => 'Kertas Foto Copy A4 80 Gram', 'satuan' => 'Rim', 'kategori_atk_id' => '12'],
            ['name' => 'Kop Surat Logo Bintang, Uk. F4 tanpa alamat/beralamat (018)', 'satuan' => 'Rim', 'kategori_atk_id' => '12'],
            ['name' => 'Kop Surat Logo Kementerian Sekretariat Negara RI, Sekretariat Wakil Presiden, Beralamat Uk. A4', 'satuan' => 'Rim', 'kategori_atk_id' => '12'],
            ['name' => 'Kop Surat Logo Wakil Presiden RI, Ukuran F4 poli Embos Bahasa Indonesia', 'satuan' => 'Rim', 'kategori_atk_id' => '12'],
            ['name' => 'Kop Surat Logo Wakil Presiden RI, Ukuran A4 poli Embos Bahasa Indonesia', 'satuan' => 'Rim', 'kategori_atk_id' => '12'],
            ['name' => 'Kop Surat Logo Wakil Presiden RI, Ukuran A4 poli Embos Bahasa Inggris', 'satuan' => 'Rim', 'kategori_atk_id' => '12'],
            ['name' => 'Kop Surat Logo Wakil Presiden RI, Ukuran B5 poli Embos Bahasa Indonesia', 'satuan' => 'Rim', 'kategori_atk_id' => '12'],
            ['name' => 'Kop Surat Logo Wakil Presiden RI, Ukuran A5 poli Embos Bahasa Indonesia', 'satuan' => 'Rim', 'kategori_atk_id' => '12'],
            ['name' => 'Dus Arsip standar warna coklat polos ukuran: 380mm x 180mm x 280mm', 'satuan' => 'Buah', 'kategori_atk_id' => '13'],
            ['name' => 'Karton Linen Putih Ukuran A2', 'satuan' => 'Rim', 'kategori_atk_id' => '13'],
            ['name' => 'Kertas Cover Buffallow F4', 'satuan' => 'Pac', 'kategori_atk_id' => '13'],
            ['name' => 'Cover Plastik Uk. F4', 'satuan' => 'Pac', 'kategori_atk_id' => '13'],
            ['name' => 'Kertas Sampul/ Kertas Samson', 'satuan' => 'Lembar', 'kategori_atk_id' => '13'],
            ['name' => 'Amplop Polos Cabinet No.110', 'satuan' => 'Dus', 'kategori_atk_id' => '14'],
            ['name' => 'Amplop Polos Cabinet No.90', 'satuan' => 'Dus', 'kategori_atk_id' => '14'],
            ['name' => 'Amplop Putih Cabinet Wapres 14x24 Bahasa Indonesia', 'satuan' => 'Buah', 'kategori_atk_id' => '14'],
            ['name' => 'Amplop Putih Cabinet Wapres 14x24 Bahasa Inggris', 'satuan' => 'Buah', 'kategori_atk_id' => '14'],
            ['name' => 'Amplop Coklat F4 Logo Bintang Setwapres', 'satuan' => 'Buah', 'kategori_atk_id' => '14'],
            ['name' => 'Amplop Coklat A3 Logo Bintang, Setwapres', 'satuan' => 'Buah', 'kategori_atk_id' => '14'],
            ['name' => 'Amplop Coklat kecil Logo Bintang, Setwapres', 'satuan' => 'Pac', 'kategori_atk_id' => '14'],
            ['name' => 'Amplop Coklat kecil polos Uk. 11 x 24cm (isi 100 pcs)', 'satuan' => 'Pac', 'kategori_atk_id' => '14'],
            ['name' => 'Amplop coklat polos ukuran: 43cm x 33cm (Isi 100 lbr) Uk. A3', 'satuan' => 'Buah', 'kategori_atk_id' => '14'],
            ['name' => 'Amplop coklat polos ukuran: 35cm x 24cm (Isi 100 lbr) Uk. Folio', 'satuan' => 'Pack', 'kategori_atk_id' => '14'],
            ['name' => 'Amplop coklat polos ukuran: 30cm x 21,5cm (Isi 100 lbr) Uk. A4', 'satuan' => 'Pack', 'kategori_atk_id' => '14'],
            ['name' => 'Amplop coklat polos ukuran: kabinet Tricom', 'satuan' => 'Pack', 'kategori_atk_id' => '14'],
            ['name' => 'Amplop coklat polos ukuran: 1/2 folio Tricom', 'satuan' => 'Pack', 'kategori_atk_id' => '14'],
            ['name' => 'Kop Surat Logo Bintang Kemensetneg, Setwapres (016)', 'satuan' => 'Rim', 'kategori_atk_id' => '15'],
            ['name' => 'Kertas HVS Warna Uk.F4/A4', 'satuan' => 'Pac', 'kategori_atk_id' => '16'],
            ['name' => 'Label No.124 Tom & Jerry', 'satuan' => 'Pac', 'kategori_atk_id' => '16'],
            ['name' => 'Label No.121 Tom & Jerry', 'satuan' => 'Pac', 'kategori_atk_id' => '16'],
            ['name' => 'Label No.103 Tom & Jerry', 'satuan' => 'Pad', 'kategori_atk_id' => '16'],
            ['name' => 'Label No.120 Tom & Jerry', 'satuan' => 'Pac', 'kategori_atk_id' => '16'],
            ['name' => 'Foto Paper Mitsubhisi Uk. A4', 'satuan' => 'Pac', 'kategori_atk_id' => '17'],
            ['name' => 'Foto Paper Mitsubhisi Uk. A3 Isi 10 Lembar', 'satuan' => 'Pac', 'kategori_atk_id' => '17'],
            ['name' => 'Kertas cetak Foto FUJI FILM ASK Media Set', 'satuan' => 'Rol', 'kategori_atk_id' => '17'],
            ['name' => 'Thermal U-FAX Uk. 80 x 80', 'satuan' => 'Rol', 'kategori_atk_id' => '17'],
            ['name' => 'Countinous Form 91/2x11 (5 Ply)', 'satuan' => 'Dus', 'kategori_atk_id' => '18'],
            ['name' => 'Toner Laserjet HP Q7553A Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet HP CB436A Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet HP CB540A Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet HP CB541A Cyan', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet HP CB542A Yellow', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet HP CB543A Magenta', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet 05A HP CE505A Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet 131A HP CF210A Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet 131A HP CF211A Cyan', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet 131A HP CF212A Yellow', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet 131A HP CF213A Magenta', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta Deskjet HP 98 Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta Deskjet HP 95 Color', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta OfficeJet HP 970 Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta OfficeJet HP 971 Cyan', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta OfficeJet HP 971 Yellow', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta OfficeJet HP 971 Magenta', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet 400 HP CE280A Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner HP Laserjet Pro 400 color 305A HP CE410A Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner HP Laserjet Pro 400 color 305A HP CE411A Cyan', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner HP Laserjet Pro 400 color 305A HP CE412A Yellow', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner HP Laserjet Pro 400 color 305A HP CE413A Magenta', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta HP 704 Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta HP 704 Color', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta Printer PageWide Pro HP 975x Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta Printer PageWide Pro HP 975x Cyan', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta Printer PageWide Pro HP 975x Yellow', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta Printer PageWide Pro HP 975x Magenta', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet MFP177A Color 130A HP CF350A Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet MFP177A Color 130A HP CF351A Cyan', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet MFP177A Color 130A HP CF352A Yellow', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet MFP177A Color 130A HP CF353A Magenta', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta GI 790 Black', 'satuan' => 'Tube', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta GI 790 Cyan', 'satuan' => 'Tube', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta GI 790 Yellow', 'satuan' => 'Tube', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta GI 790 Magenta', 'satuan' => 'Tube', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta HP 62 Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta HP 62 Color', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet  HP CF219A Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet  26A Type CF226A Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta Epson 001 Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta Epson 001 Cyan', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta Epson 001 Yellow', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta Epson 001 Magenta', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet 206A HP W2110A Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet 206A HP W2111A Cyan', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet 206A HP W2112A Yellow', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet 206A HP W2113A Magenta', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta Epson 289 Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta Epson 290 Color', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Epson Label 12mm Black on White', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Epson Label 18mm Black on White', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Epson Label 24mm Black on White', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Epson Label 36mm Black on White', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet Data Print 508 Type CF360A Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet Data Print 508 Type CF361A Cyan', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet Data Print 508 Type CF362A Yellow', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner Laserjet  Data Print 17A Type CF217A Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner HP Laserjet HP 204A, CF510A Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner HP Laserjet HP 204A, CF511A Cyan', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner HP Laserjet HP 204A, CF512A Magenta', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner HP Laserjet HP 204A, CF513A Yellow', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner HP Laserjet HP 222A, W2220A Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner HP Laserjet HP 222A, W2221A Cyan', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner HP Laserjet HP 222A, W2222A Yellow', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner HP Laserjet HP 222A, W2223A Magenta', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner HP Laserjet HP 119A, W2090A Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner HP Laserjet HP 119A, W2091A Cyan', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner HP Laserjet HP 119A, W2092A Yellow', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Toner HP Laserjet HP 119A, W2093A Magenta', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta Epson T11F1 Black', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta Epson T11F2 Cyan', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta Epson T11F3 Magenta (Epson 673, L800 Magenta)', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'Tinta Epson T11F4 Yellow', 'satuan' => 'Buah', 'kategori_atk_id' => '19'],
            ['name' => 'CDR-R Verbatim 52 X 700 MB', 'satuan' => 'Buah', 'kategori_atk_id' => '20'],
            ['name' => 'Tali Benang Rami', 'satuan' => 'Rol', 'kategori_atk_id' => '21'],
            ['name' => 'Clear Holder Ukuran A4', 'satuan' => 'Buah', 'kategori_atk_id' => '11'],
            ['name' => 'Baterai Besar', 'satuan' => 'Buah', 'kategori_atk_id' => '22'],
            ['name' => 'Baterai Energizer 9 Volt', 'satuan' => 'Buah', 'kategori_atk_id' => '22'],
            ['name' => 'Baterai Sedang/Tanggung R14C, 1,5 Volt', 'satuan' => 'Buah', 'kategori_atk_id' => '22'],
            ['name' => 'Baterai Energizer MAX,  AA/AAA Isi 2 Buah', 'satuan' => 'Set', 'kategori_atk_id' => '22'],
            ['name' => 'Baterai Laser Pointer Maxell Lr41', 'satuan' => 'Buah', 'kategori_atk_id' => '22'],
            ['name' => 'Baterai  A23A 12 Volt', 'satuan' => 'Buah', 'kategori_atk_id' => '22'],
            ['name' => 'Baterai Energizer/CMOS 2032 (Di Sakti Panasonic 2025)', 'satuan' => 'Buah', 'kategori_atk_id' => '22'],
            ['name' => 'Max Stapler HD.10 ', 'satuan' => 'Buah', 'kategori_atk_id' => '11'],
            ['name' => 'Isi Staples No. 10 Max ', 'satuan' => 'Dus kecil', 'kategori_atk_id' => '11'],
            ['name' => 'Paper Bag Batik Jumbo Kiky Uk. 450x328x130mm ', 'satuan' => 'Pack', 'kategori_atk_id' => '11'],
            ['name' => 'Dispenser Lakban TD-2 Joyco', 'satuan' => 'Buah', 'kategori_atk_id' => '11'],
        ];

        DaftarAtk::query()->delete();

        foreach ($atks as $key => $value) {
            DaftarAtk::create([
                'kode_unit' => '02',
                'name' => $value['name'],
                'kategori_atk_id' => $value['kategori_atk_id'],
                'satuan' => $value['satuan'],
            ]);
        }
    }
}
