<?php

namespace Database\Seeders;

use App\Models\DaftarAtk;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DaftarAtkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['kode_atk' => 'AT_051', 'name' => 'Bollpoint Bolliner Pilot', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_052', 'name' => 'Bollpoint Boxy Uniball', 'category' => 'Alat Tulis', 'satuan' => 'Lusin'],
            ['kode_atk' => 'AT_053', 'name' => 'Bollpoint Hi-Tech Point V.5', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_054', 'name' => 'Bollpoint Uniball Signo', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_055', 'name' => 'Pensil Staedtler 2B', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_056', 'name' => 'Spidol Gold/Silver besar', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_057', 'name' => 'Spidol Permanent Art Line 107R (Merah)', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_058', 'name' => 'Spidol Whiteboard/ Artline 157R merah/Spidol Artline 500', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_059', 'name' => 'Spidol Snowman Kecil', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_060', 'name' => 'Bollpoint Boldliner 1.0 Hitam/Biru', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_061', 'name' => 'Pulpen Zebra Sarasa 0,5', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_062', 'name' => 'Bollpoin Standar P5', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_063', 'name' => 'Spidol Snowman Whiteboard', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_064', 'name' => 'Bollpoint Uniball Signo Broad', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_065', 'name' => 'Spidol Snowman AG-12 Permanent', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_066', 'name' => 'Stabillo Swing Cool', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_067', 'name' => 'Zebra Isi ulang Pulpen 0,7 mm hitam', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_068', 'name' => 'Bollpoint Boldliner Elite warna Biru', 'category' => 'Alat Tulis', 'satuan' => 'Lusin'],
            ['kode_atk' => 'TTS_069', 'name' => 'Tinta Stempel', 'category' => 'Tinta Tulis, Tinta Stempel', 'satuan' => 'Tube'],
            ['kode_atk' => 'TTS_070', 'name' => 'Tinta Stempel Trodat 7011', 'category' => 'Tinta Tulis, Tinta Stempel', 'satuan' => 'Tube'],
            ['kode_atk' => 'PK_071', 'name' => 'Binder Clips No.105', 'category' => 'Penjepit Kertas', 'satuan' => 'Dus kecil'],
            ['kode_atk' => 'PK_072', 'name' => 'Binder Clips No.107', 'category' => 'Penjepit Kertas', 'satuan' => 'Dus kecil'],
            ['kode_atk' => 'PK_073', 'name' => 'Binder Clips No.111', 'category' => 'Penjepit Kertas', 'satuan' => 'Dus kecil'],
            ['kode_atk' => 'PK_074', 'name' => 'Binder Clips No.155', 'category' => 'Penjepit Kertas', 'satuan' => 'Dus kecil'],
            ['kode_atk' => 'PK_075', 'name' => 'Binder Clips No. 200', 'category' => 'Penjepit Kertas', 'satuan' => 'Dus kecil'],
            ['kode_atk' => 'PK_076', 'name' => 'Binder Clips No.260', 'category' => 'Penjepit Kertas', 'satuan' => 'Dus kecil'],
            ['kode_atk' => 'PK_077', 'name' => 'Clips Paper No.3', 'category' => 'Penjepit Kertas', 'satuan' => 'Dus kecil'],
            ['kode_atk' => 'PK_078', 'name' => 'Spiral kawat ring putih 3/8', 'category' => 'Penjepit Kertas', 'satuan' => 'Box'],
            ['kode_atk' => 'PK_079', 'name' => 'Spiral kawat ring putih 7/16', 'category' => 'Penjepit Kertas', 'satuan' => 'Box'],
            ['kode_atk' => 'PK_080', 'name' => 'Penghapus Karet Staedtler', 'category' => 'Penghapus/Korektor', 'satuan' => 'Buah'],
            ['kode_atk' => 'PK_081', 'name' => 'Penghapus Whiteboard', 'category' => 'Penghapus/Korektor', 'satuan' => 'Buah'],
            ['kode_atk' => 'PK_082', 'name' => 'Penghapus Pita IBM/Carera', 'category' => 'Penghapus/Korektor', 'satuan' => 'Rol'],
            ['kode_atk' => 'PK_083', 'name' => 'Remover', 'category' => 'Penghapus/Korektor', 'satuan' => 'Buah'],
            ['kode_atk' => 'PK_084', 'name' => 'Tip Ex Pen/Correction Pen ZL62-W Pentel', 'category' => 'Penghapus/Korektor', 'satuan' => 'Buah'],
            ['kode_atk' => 'PK_085', 'name' => 'Tip ex Joyco CT-522', 'category' => 'Penghapus/Korektor', 'satuan' => 'Buah'],
            ['kode_atk' => 'PK_086', 'name' => 'Penghapus Faber Castel 20-L', 'category' => 'Penghapus/Korektor', 'satuan' => 'Buah'],
            ['kode_atk' => 'BT_087', 'name' => 'Bloknote/Memo Dinas Ukuran A5', 'category' => 'Buku Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'BT_088', 'name' => 'Bloknote/Memo Dinas Kecil Warna Orange', 'category' => 'Buku Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'BT_089', 'name' => 'Buku Agenda Surat Masuk Uk F4 Merah Isi 300 Lbr', 'category' => 'Buku Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'BT_090', 'name' => 'Buku Expedisi Merah Isi 300 Lbr', 'category' => 'Buku Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'BT_091', 'name' => 'Buku Agenda Quarto Isi 100 Lembar', 'category' => 'Buku Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'BT_092', 'name' => 'Buku Agenda Folio Isi 100 Lembar', 'category' => 'Buku Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'BT_093', 'name' => 'Buku Expedisi Isi 100 Lembar', 'category' => 'Buku Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'BT_094', 'name' => 'Bloknote Paperline ukuran A4', 'category' => 'Buku Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'BT_095', 'name' => 'Bloknote Paperline ukuran A4', 'category' => 'Buku Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'BT_096', 'name' => 'Bloknote A5 Merk Paperline', 'category' => 'Buku Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'BT_097', 'name' => 'Bloknote/Memo kecil cover putih Logo Kemensetneg RI, Setwapres', 'category' => 'Buku Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'BT_098', 'name' => 'Bloknote/Memo kecil cover hitam Logo Wakil Presiden RI', 'category' => 'Buku Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'OM_099', 'name' => 'Box File Jumbo Bindex', 'category' => 'Ordner Dan Map', 'satuan' => 'Buah'],
            ['kode_atk' => 'OM_100', 'name' => 'Map Daichi Clear Sleves 9001 uk. A4', 'category' => 'Ordner Dan Map', 'satuan' => 'Buah'],
            ['kode_atk' => 'OM_101', 'name' => 'Map Bussiness File Plastik Ukuran A4', 'category' => 'Ordner Dan Map', 'satuan' => 'Buah'],
            ['kode_atk' => 'OM_102', 'name' => 'Map Bussiness File Plastik Ukuran F4 Gunshu 390F', 'category' => 'Ordner Dan Map', 'satuan' => 'Buah'],
            ['kode_atk' => 'OM_103', 'name' => 'Ordner Merk Bambi 1010 (Di Sakti 2121)', 'category' => 'Ordner Dan Map', 'satuan' => 'Buah'],
            ['kode_atk' => 'OM_104', 'name' => 'Ordner Folio 717 Bindex', 'category' => 'Ordner Dan Map', 'satuan' => 'Buah'],
            ['kode_atk' => 'OM_105', 'name' => 'Standar Buku Merk Lion', 'category' => 'Ordner Dan Map', 'satuan' => 'Set'],
            ['kode_atk' => 'OM_106', 'name' => 'Stop Map Polos 5002', 'category' => 'Ordner Dan Map', 'satuan' => 'Exp'],
            ['kode_atk' => 'OM_107', 'name' => 'Stop Map Putih Logo Bintang Kemsetneg Setwapres, Art Carton Putih', 'category' => 'Ordner Dan Map', 'satuan' => 'Buah'],
            ['kode_atk' => 'OM_108', 'name' => 'Map Bp. Wapres bahan Art Carton Ukuran A5', 'category' => 'Ordner Dan Map', 'satuan' => 'Buah'],
            ['kode_atk' => 'OM_109', 'name' => 'Map Plastik Daichi file 9002 uk. F4', 'category' => 'Ordner Dan Map', 'satuan' => 'Buah'],
            ['kode_atk' => 'OM_110', 'name' => 'Map Folder Arsip Bahan kartu tik', 'category' => 'Ordner Dan Map', 'satuan' => 'Buah'],
            ['kode_atk' => 'OM_111', 'name' => 'Plastik Bantex Uk. F4 (isi 100 lembar)', 'category' => 'Ordner Dan Map', 'satuan' => 'Pack'],
            ['kode_atk' => 'OM_112', 'name' => 'Plastik Bantex uk: A4 isi 100/Pack', 'category' => 'Ordner Dan Map', 'satuan' => 'Pack'],
            ['kode_atk' => 'OM_113', 'name' => 'Map gantung Fujita ukuran F4 isi 50 buah', 'category' => 'Ordner Dan Map', 'satuan' => 'Pack/Dus'],
            ['kode_atk' => 'OM_114', 'name' => 'Clear Holder Ukuran F4 CH.40', 'category' => 'Ordner Dan Map', 'satuan' => 'Buah'],
            ['kode_atk' => 'OM_115', 'name' => 'Map Bp. Wakil Presiden RI warna hitam', 'category' => 'Ordner Dan Map', 'satuan' => 'Buah'],
            ['kode_atk' => 'OM_116', 'name' => 'Map lipat Acordion warna cream lis linen merah', 'category' => 'Ordner Dan Map', 'satuan' => 'Buah'],
            ['kode_atk' => 'PG_117', 'name' => 'Penggaris Plastik 30 Cm', 'category' => 'Penggaris', 'satuan' => 'Buah'],
            ['kode_atk' => 'PG_118', 'name' => 'Penggaris Besi 30 Cm', 'category' => 'Penggaris', 'satuan' => 'Buah'],
            ['kode_atk' => 'PG_119', 'name' => 'Penggaris Plastik 50 Cm', 'category' => 'Penggaris', 'satuan' => 'Buah'],
            ['kode_atk' => 'CT_120', 'name' => 'Cutter Besar L -500', 'category' => 'Cutter (Alat Tulis Kantor)', 'satuan' => 'Buah'],
            ['kode_atk' => 'CT_121', 'name' => 'Cutter Kecil A- 300', 'category' => 'Cutter (Alat Tulis Kantor)', 'satuan' => 'Buah'],
            ['kode_atk' => 'PMK_122', 'name' => 'Pita Olympia Carera (AX200)', 'category' => 'Pita Mesin Ketik', 'satuan' => 'Rol'],
            ['kode_atk' => 'AP_123', 'name' => 'Celotape uk. 1" Daimaru', 'category' => 'Alat Perekat', 'satuan' => 'Rol'],
            ['kode_atk' => 'AP_124', 'name' => 'Double Tape Uk. 1"', 'category' => 'Alat Perekat', 'satuan' => 'Rol'],
            ['kode_atk' => 'AP_125', 'name' => 'Lem cair Joyco', 'category' => 'Alat Perekat', 'satuan' => 'Tube'],
            ['kode_atk' => 'AP_126', 'name' => 'Lem Pasta', 'category' => 'Alat Perekat', 'satuan' => 'Tube'],
            ['kode_atk' => 'AP_127', 'name' => 'Lem Spraymount Artist Besar 290 Gram', 'category' => 'Alat Perekat', 'satuan' => 'Kaleng'],
            ['kode_atk' => 'AP_128', 'name' => 'Lem UHU Stick 40 gram (Pritt 40 gram)', 'category' => 'Alat Perekat', 'satuan' => 'Buah'],
            ['kode_atk' => 'AP_129', 'name' => 'Lak Band Kain Hitam', 'category' => 'Alat Perekat', 'satuan' => 'Buah'],
            ['kode_atk' => 'AP_130', 'name' => 'Lak Band Coklat plastik', 'category' => 'Alat Perekat', 'satuan' => 'Buah'],
            ['kode_atk' => 'AP_131', 'name' => 'Lem Fox 1 kg', 'category' => 'Alat Perekat', 'satuan' => 'Tube'],
            ['kode_atk' => 'AP_132', 'name' => 'Cellotape bening/besar ukuran 2 inc', 'category' => 'Alat Perekat', 'satuan' => 'Buah'],
            ['kode_atk' => 'AP_133', 'name' => 'Lakban bening Daimaru ukuran 2 inc', 'category' => 'Alat Perekat', 'satuan' => 'Buah'],
            ['kode_atk' => 'AP_134', 'name' => 'Lakban hitam', 'category' => 'Alat Perekat', 'satuan' => 'Roll'],
            ['kode_atk' => 'KH_135', 'name' => 'Kertas Foto Copy A3 80 Gram', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_136', 'name' => 'Kertas Foto Copy F4 80 Gram', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_137', 'name' => 'Kertas Foto Copy A4 80 Gram', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_138', 'name' => 'Kertas Foto Copy A5 80 Gram', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_139', 'name' => 'Kop Surat Logo Bintang, Uk. F4 tanpa alamat/beralamat (018)', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_140', 'name' => 'Kop Surat Logo Wakil Presiden RI, Ukuran F4 poli Embos Bahasa Indonesia', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_141', 'name' => 'Kop Surat Logo Wakil Presiden RI, Ukuran A4 poli Embos Bahasa Indonesia', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_142', 'name' => 'Kop Surat Logo Wakil Presiden RI, Ukuran A4 poli Embos Bahasa Inggris', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_143', 'name' => 'Kop Surat Logo Wakil Presiden RI, Ukuran B5 poli Embos Bahasa Indonesia', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_144', 'name' => 'Kertas HVS Ukuran B5', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'AL_145', 'name' => 'Bak Stempel', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Buah'],
            ['kode_atk' => 'AL_146', 'name' => 'Isi Max Stapler No.3. 1M', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Dus'],
            ['kode_atk' => 'AL_147', 'name' => 'Isi Cutter Kecil A-100', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Tube'],
            ['kode_atk' => 'AL_148', 'name' => 'Max Stapler HD.50', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Buah'],
            ['kode_atk' => 'AL_149', 'name' => 'Magnit White Board', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Buah'],
            ['kode_atk' => 'AL_150', 'name' => 'Pembolong Kertas Besar No.85', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Buah'],
            ['kode_atk' => 'AL_151', 'name' => 'Rautan Pensil Carl Angel V', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Buah'],
            ['kode_atk' => 'AL_152', 'name' => 'Tempat Pensil (Caddy Set) Kenko 8312', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Buah'],
            ['kode_atk' => 'AL_153', 'name' => 'Pembolong Kertas Kecil', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Buah'],
            ['kode_atk' => 'AL_154', 'name' => 'Rautan Pencil Carl Angel Kecil', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Buah'],
            ['kode_atk' => 'AL_155', 'name' => 'Isi Cutter L500 Setara Kenko', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Tube'],
            ['kode_atk' => 'AL_156', 'name' => 'Post it Sign here', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Pad'],
            ['kode_atk' => 'AL_157', 'name' => 'Post-it No.654 (tampungan)', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Pad'],
            ['kode_atk' => 'AL_158', 'name' => 'Post-it No.655 (tampungan)', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Pad'],
            ['kode_atk' => 'AL_159', 'name' => 'Post-it Pronto', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Pad'],
            ['kode_atk' => 'AL_160', 'name' => 'Gunting Sedang Joyko SC-838', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Buah'],
            ['kode_atk' => 'AL_161', 'name' => 'Dispenser Isolasi TD=103 Joyco', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Buah'],
            ['kode_atk' => 'AL_162', 'name' => 'Tempat Cellotape 1 inc', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Buah'],
            ['kode_atk' => 'AL_163', 'name' => 'Gunting Besar Joyko SC-838', 'category' => 'Alat Tulis Kantor Lainnya', 'satuan' => 'Buah'],
            ['kode_atk' => 'KH_164', 'name' => 'Kertas Foto Copy A3 80 Gram', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_165', 'name' => 'Kertas Foto Copy F4 80 Gram', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_166', 'name' => 'Kertas Foto Copy A4 80 Gram', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_167', 'name' => 'Kertas Foto Copy A5 80 Gram', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_168', 'name' => 'Kop Surat Logo Bintang, Uk. F4 tanpa alamat/beralamat (018)', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_169', 'name' => 'Kop Surat Logo Wakil Presiden RI, Ukuran F4 poli Embos Bahasa Indonesia', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_170', 'name' => 'Kop Surat Logo Wakil Presiden RI, Ukuran A4 poli Embos Bahasa Indonesia', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_171', 'name' => 'Kop Surat Logo Wakil Presiden RI, Ukuran A4 poli Embos Bahasa Inggris', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_172', 'name' => 'Kop Surat Logo Wakil Presiden RI, Ukuran B5 poli Embos Bahasa Indonesia', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KH_173', 'name' => 'Kertas HVS Ukuran B5', 'category' => 'Kertas Hvs', 'satuan' => 'Rim'],
            ['kode_atk' => 'KC_174', 'name' => 'Dus Arsip standar warna coklat polos ukuran: 380mm x 180mm x 280mm', 'category' => 'Kertas Cover', 'satuan' => 'Buah'],
            ['kode_atk' => 'KC_175', 'name' => 'Dus Arsip standar warna coklat dalam warna putih ukuran: 380mm x 100mm x 280mm', 'category' => 'Kertas Cover', 'satuan' => 'Buah'],
            ['kode_atk' => 'KC_176', 'name' => 'Cover Plastik Uk. F4', 'category' => 'Kertas Cover', 'satuan' => 'Packk'],
            ['kode_atk' => 'KC_177', 'name' => 'Kertas Sampul/ Kertas Samson', 'category' => 'Kertas Cover', 'satuan' => 'Lembar'],
            ['kode_atk' => 'CF_178', 'name' => 'Countinous Form 91/2x11 (5 Ply)', 'category' => 'Continuous Form', 'satuan' => 'Dus'],
            ['kode_atk' => 'AP_179', 'name' => 'Amplop Polos Cabinet No.110', 'category' => 'Amplop', 'satuan' => 'Dus'],
            ['kode_atk' => 'AP_180', 'name' => 'Amplop Polos Cabinet No.90', 'category' => 'Amplop', 'satuan' => 'Dus'],
            ['kode_atk' => 'AP_181', 'name' => 'Amplop Polos Coklat uk.A3', 'category' => 'Amplop', 'satuan' => 'Lembar'],
            ['kode_atk' => 'AP_182', 'name' => 'Amplop Putih Cabinet Wapres 14x24 Bahasa Indonesia', 'category' => 'Amplop', 'satuan' => 'Buah'],
            ['kode_atk' => 'AP_183', 'name' => 'Amplop Putih Cabinet Wapres 14x24 Bahasa Inggris', 'category' => 'Amplop', 'satuan' => 'Buah'],
            ['kode_atk' => 'AP_184', 'name' => 'Amplop Coklat F4 Logo Bintang Setwapres', 'category' => 'Amplop', 'satuan' => 'Buah'],
            ['kode_atk' => 'AP_185', 'name' => 'Amplop Coklat A3 Logo Bintang, Setwapres', 'category' => 'Amplop', 'satuan' => 'Buah'],
            ['kode_atk' => 'AP_186', 'name' => 'Amplop Coklat kecil Logo Bintang, Setwapres', 'category' => 'Amplop', 'satuan' => 'Pack'],
            ['kode_atk' => 'AP_187', 'name' => 'Amplop Coklat kecil polos Uk. 11 x 24cm (isi 100 pcs)', 'category' => 'Amplop', 'satuan' => 'Pack'],
            ['kode_atk' => 'KS_188', 'name' => 'Kop Surat Logo Bintang Kemensetneg, Setwapres (016)', 'category' => 'Kop Surat', 'satuan' => 'Rim'],
            ['kode_atk' => 'KS_189', 'name' => 'Kop Surat Logo Bintang, Uk. A4 tanpa alamat/beralamat (017)', 'category' => 'Kop Surat', 'satuan' => 'Rim'],
            ['kode_atk' => 'KS_190', 'name' => 'Kop Surat Logo Bintang, Uk. F4 tanpa alamat (018)', 'category' => 'Kop Surat', 'satuan' => 'Rim'],
            ['kode_atk' => 'KC_191', 'name' => 'Kertas HVS Warna Uk.F4/A4', 'category' => 'Kertas Dan Cover Lainnya', 'satuan' => 'Pack'],
            ['kode_atk' => 'KC_192', 'name' => 'Label No.124 Tom & Jerry', 'category' => 'Kertas Dan Cover Lainnya', 'satuan' => 'Pack'],
            ['kode_atk' => 'KC_193', 'name' => 'Label No.121 Tom & Jerry', 'category' => 'Kertas Dan Cover Lainnya', 'satuan' => 'Pack'],
            ['kode_atk' => 'KC_194', 'name' => 'Label No.103 Tom & Jerry', 'category' => 'Kertas Dan Cover Lainnya', 'satuan' => 'Pad'],
            ['kode_atk' => 'KC_195', 'name' => 'Label No.120 Tom & Jerry', 'category' => 'Kertas Dan Cover Lainnya', 'satuan' => 'Pack'],
            ['kode_atk' => 'BCL_196', 'name' => 'Foto Paper Mitsubhisi Uk. A4', 'category' => 'Bahan Cetak Lainnya', 'satuan' => 'Pack'],
            ['kode_atk' => 'BCL_197', 'name' => 'Foto Paper Mitsubhisi Uk. A3 Isi 10 Lembar', 'category' => 'Bahan Cetak Lainnya', 'satuan' => 'Pack'],
            ['kode_atk' => 'TDT_198', 'name' => 'Toner HP Laserjet Pro 400 color 305A HP CE411A Cyan', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_199', 'name' => 'Toner HP Laserjet Pro 400 color 305A HP CE412A Yellow', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_200', 'name' => 'Toner HP Laserjet Pro 400 color 305A HP CE413A Magenta', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_201', 'name' => 'Toner Laserjet HP Q7553A Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_202', 'name' => 'Toner Laserjet HP CB436A Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_203', 'name' => 'Toner Laserjet HP CB540A Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_204', 'name' => 'Toner Laserjet HP CB541A Cyan', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_205', 'name' => 'Toner Laserjet HP CB542A Yellow', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_206', 'name' => 'Toner Laserjet HP CB543A Magenta', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_207', 'name' => 'Tinta Canon PG-35 Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_208', 'name' => 'Tinta Canon CLI-36 Colour', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_209', 'name' => 'Toner Laserjet 05A HP CE505A Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_210', 'name' => 'Toner Laserjet HP CF278A Black (Di Saskti CE278A Black)', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_211', 'name' => 'Toner Laserjet HP CE321A Cyan', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_212', 'name' => 'Toner Laserjet HP CE322A Yellow', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_213', 'name' => 'Toner Laserjet HP CE323A Magenta', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_214', 'name' => 'Toner Laserjet 131A HP CF210A Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_215', 'name' => 'Toner Laserjet 131A HP CF211A Cyan', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_216', 'name' => 'Toner Laserjet 131A HP CF212A Yellow', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_217', 'name' => 'Toner Laserjet 131A HP CF213A Magenta', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_218', 'name' => 'Tinta Deskjet HP 98 Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_219', 'name' => 'Tinta Deskjet HP 95 Color', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_220', 'name' => 'Tinta OfficeJet HP 970 Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_221', 'name' => 'Tinta OfficeJet HP 971 Cyan', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_222', 'name' => 'Tinta OfficeJet HP 971 Yellow', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_223', 'name' => 'Tinta OfficeJet HP 971 Magenta', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_224', 'name' => 'Toner Laserjet 400 HP CE280A Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_225', 'name' => 'Toner Laserjet CP1025 HP CE310A Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_226', 'name' => 'Toner Laserjet CP1025 HP CE311A Cyan', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_227', 'name' => 'Toner Laserjet CP1025 Color HP CE312A Yellow', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_228', 'name' => 'Toner Laserjet CP1025 Color HP CE313A Magenta', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_229', 'name' => 'Tinta HP 704 Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_230', 'name' => 'Tinta HP 704 Color', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_231', 'name' => 'Tinta Printer PageWide Pro HP 975x Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_232', 'name' => 'Tinta Printer PageWide Pro HP 975x Cyan', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_233', 'name' => 'Tinta Printer PageWide Pro HP 975x Yellow', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_234', 'name' => 'Tinta Printer PageWide Pro HP 975x Magenta', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_235', 'name' => 'Toner Laserjet MFP177A Color 130A HP CF350A Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_236', 'name' => 'Toner Laserjet MFP177A Color 130A HP CF351A Cyan', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_237', 'name' => 'Toner Laserjet MFP177A Color 130A HP CF352A Yellow', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_238', 'name' => 'Toner Laserjet MFP177A Color 130A HP CF353A Magenta', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_239', 'name' => 'Toner Laserjet 30A HP CF230A Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_240', 'name' => 'Toner Laserjet 30A HP CF232A Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_241', 'name' => 'Tinta GI 790 Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Tube'],
            ['kode_atk' => 'TDT_242', 'name' => 'Tinta GI 790 Cyan', 'category' => 'Toner Dan Tinta', 'satuan' => 'Tube'],
            ['kode_atk' => 'TDT_243', 'name' => 'Tinta GI 790 Yellow', 'category' => 'Toner Dan Tinta', 'satuan' => 'Tube'],
            ['kode_atk' => 'TDT_244', 'name' => 'Tinta GI 790 Magenta', 'category' => 'Toner Dan Tinta', 'satuan' => 'Tube'],
            ['kode_atk' => 'TDT_245', 'name' => 'Tinta HP 62 Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_246', 'name' => 'Tinta HP 62 Color', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_247', 'name' => 'Toner Laserjet HP CF219A Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_248', 'name' => 'Toner Laserjet HP CF226A Black (26A)', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_249', 'name' => 'Tinta Epson 001 Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_250', 'name' => 'Tinta Epson 001 Cyan', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_251', 'name' => 'Tinta Epson 001 Yellow', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_252', 'name' => 'Tinta Epson 001 Magenta', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_253', 'name' => 'Toner Laserjet 206A HP W2110A Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_254', 'name' => 'Toner Laserjet 206A HP W2111A Cyan', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_255', 'name' => 'Toner Laserjet 206A HP W2112A Yellow', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_256', 'name' => 'Toner Laserjet 206A HP W2113A Magenta', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_257', 'name' => 'Epson Label 12mm Black on White', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_258', 'name' => 'Epson Label 18mm Black on White', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_259', 'name' => 'Epson Label 24mm Black on White', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_260', 'name' => 'Epson Label 36mm Black on White', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_261', 'name' => 'Tinta Epson 289 Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_262', 'name' => 'Tinta Epson 290 Color', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_263', 'name' => 'Toner Laserjet Data Print 508 Type CF360A Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_264', 'name' => 'Toner Laserjet Data Print 508 Type CF361A Cyan', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_265', 'name' => 'Toner Laserjet Data Print 508 Type CF362A Yellow', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_266', 'name' => 'Toner Laserjet Data Print 17A Type CF217A Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_267', 'name' => 'Tinta Epson T11F1 Black', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_268', 'name' => 'Tinta Epson T11F2 Cyan', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_269', 'name' => 'Tinta Epson T11F3 Magenta (Epson 673, L800 Magenta)', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'TDT_270', 'name' => 'Tinta Epson T11F4 Yellow', 'category' => 'Toner Dan Tinta', 'satuan' => 'Buah'],
            ['kode_atk' => 'BKL_271', 'name' => 'CDR-R Verbatim 52 X 700 MB', 'category' => 'Bahan Komputer Lainnya', 'satuan' => 'Buah'],
            ['kode_atk' => 'AP_272', 'name' => 'Tali Benang Rami', 'category' => 'Alat Pengikat', 'satuan' => 'Rol'],
            ['kode_atk' => 'AP_273', 'name' => 'Clear Holder Ukuran A4', 'category' => 'Alat Pengikat', 'satuan' => 'Buah'],
            ['kode_atk' => 'BB_274', 'name' => 'Baterai Besar', 'category' => 'Batu Baterai', 'satuan' => 'Buah'],
            ['kode_atk' => 'BB_275', 'name' => 'Baterai Energizer 9 Volt', 'category' => 'Batu Baterai', 'satuan' => 'Buah'],
            ['kode_atk' => 'BB_276', 'name' => 'Baterai Sedang/Tanggung R14C, 1,5 Volt', 'category' => 'Batu Baterai', 'satuan' => 'Buah'],
            ['kode_atk' => 'BB_277', 'name' => 'Baterai Energizer MAX, AA/AAA Isi 2 Buah', 'category' => 'Batu Baterai', 'satuan' => 'Set'],
            ['kode_atk' => 'BB_278', 'name' => 'Baterai Laser Pointer Maxell Lr41', 'category' => 'Batu Baterai', 'satuan' => 'Buah'],
            ['kode_atk' => 'BB_279', 'name' => 'Baterai A23A 12 Volt', 'category' => 'Batu Baterai', 'satuan' => 'Buah'],
            ['kode_atk' => 'BB_280', 'name' => 'Baterai Energizer/CMOS 2032 (Di Sakti Panasonic 2025)', 'category' => 'Batu Baterai', 'satuan' => 'Buah'],
            ['kode_atk' => 'BB_281', 'name' => 'Max Stapler HD.10', 'category' => 'Batu Baterai', 'satuan' => 'Buah'],
            ['kode_atk' => 'BB_282', 'name' => 'Isi Staples No. 10 Max', 'category' => 'Batu Baterai', 'satuan' => 'Dus kecil'],
            ['kode_atk' => 'BB_283', 'name' => 'Paper Bag Batik Jumbo Kiky Uk. 450x328x130mm', 'category' => 'Batu Baterai', 'satuan' => 'Pack'],
            ['kode_atk' => 'BB_284', 'name' => 'Penghapus Faber Castell 20-L', 'category' => 'Batu Baterai', 'satuan' => 'Buah'],
        ];

        $datax = [
            ['kode_atk' => 'AT_051', 'name' => 'Bollpoint Bolliner Pilot', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_052', 'name' => 'Bollpoint Boxy Uniball', 'category' => 'Alat Tulis', 'satuan' => 'Lusin'],
            ['kode_atk' => 'AT_053', 'name' => 'Bollpoint Hi-Tech Point V.5', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_054', 'name' => 'Bollpoint Uniball Signo', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_055', 'name' => 'Pensil Staedtler 2B', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_056', 'name' => 'Spidol Gold/Silver besar', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
            ['kode_atk' => 'AT_057', 'name' => 'Spidol Permanent Art Line 107R (Merah)', 'category' => 'Alat Tulis', 'satuan' => 'Buah'],
        ];

        foreach ($datax as $key => $value) {
            DaftarAtk::create([
                'kode_unit' => '02',
                'name' => $value['name'],
                'kode_atk' => $value['kode_atk'],
                'category' => $value['category'],
                'satuan' => $value['satuan'],
            ]);
        }
    }
}
